#version 460
#extension GL_EXT_ray_tracing : require

layout(set = 0, binding = 0) uniform accelerationStructureEXT topLevelAS;
layout(set = 0, binding = 8, rgba16f) uniform image2D IrradianceAtlasImage;


const int PROBE_STATE_ACTIVE   = 0; //  this is for when a probe is activly collecting new scene data
const int PROBE_STATE_SLEEP    = 1; //  this is for when a probe is always hitting the skybox
const int PROBE_STATE_DISABLED = 2; //  this is for when a probe is inside an object and is not contributing meaningfully.
//A probe that is disabled can be moved so it is active

struct ProbeInformation {
    vec4 probeLocationsXYZ_ProbeState;
};


layout(set = 0, binding = 9) readonly buffer StorageBuffer {
      ProbeInformation  ProbeData[];
} SB0;

layout(set = 0, binding = 10) readonly buffer StorageBuffer2 {
   vec4 FibonacciDirections[];
} SB02;

layout (binding = 12) uniform samplerCube samplerCubeMap[2];

layout(push_constant) uniform PushConstant{
    vec4 GridBaseLocation_ScreenSizeWidth;
    vec4 ProbeSpacing_ScreenSizeHeight;
    vec4 ProbeCount;

    ///////////////////////

    int   AtlasWidthSize;  
    int   ProbeSideLength; 
    int   GutterSize;      
    int   NumRays;
    vec4 UseInfiniteBounce_infinite_bounces_multiplier_SampleCount_FrameCount;
}pc;

struct Payload {
    vec3  Color;
    float Distance;
    int   Hit;
};

layout(location = 0) rayPayloadEXT Payload payload;

vec3 GetPerpendicularVector(vec3 v) {

    return normalize(cross(v, abs(v.x) > abs(v.z) ? vec3(0.0, 0.0, 1.0) : vec3(1.0, 0.0, 0.0)
    ));
}
vec3 GetHemisphereSample(vec2 randVal, vec3 HitNormal) {
    vec3 bitangent = GetPerpendicularVector(HitNormal);
    vec3 tangent = cross(bitangent, HitNormal);
    float r = sqrt(randVal.x);
    float phi = 2.0 * 3.14159265 * randVal.y;
    
    return tangent * (r * cos(phi)) + bitangent * (r * sin(phi)) + HitNormal.xyz * sqrt(max(0.0, 1.0 - randVal.x));
}



vec2 rand2D(vec2 co) {
    co = fract(co * vec2(123.34, 345.45));
    co += dot(co, co + 34.345);
    return fract(vec2(co.x * co.y, co.x + co.y));
}

void main() {
     
    int SkyBoxIndex = int(pc.ProbeCount.w);
 
    ProbeInformation probe  = SB0.ProbeData[gl_LaunchIDEXT.y];

    vec3 probeOrigin  = probe.probeLocationsXYZ_ProbeState.xyz;
    vec3 rayDirection = SB02.FibonacciDirections[gl_LaunchIDEXT.x].xyz;
    int probeState    = int(probe.probeLocationsXYZ_ProbeState.w);


   // Trace the ray
    const uint rayFlags = gl_RayFlagsOpaqueEXT;
    const uint cullMask = 0xFF;
    const float tMin = 0.001;
    const float tMax = 10000.0;

   vec3 CubeMapIrradiance = texture(samplerCubeMap[SkyBoxIndex], rayDirection).rgb;

       if(probeState ==  PROBE_STATE_ACTIVE){
          
           payload.Hit = 0;
           payload.Color = vec3(0.0);
           payload.Distance = tMax;

          traceRayEXT(topLevelAS, rayFlags, cullMask, 0, 0, 0, probeOrigin.xyz, tMin, rayDirection, tMax, 0);

          vec3  Radiance      = payload.Color;
          float Distance      = payload.Distance;

          if(payload.Hit == 0){
              Radiance = CubeMapIrradiance;
              Distance = 1000;
             }
          imageStore(IrradianceAtlasImage, ivec2(gl_LaunchIDEXT.xy), vec4(Radiance,Distance));

       }
         else if (probeState ==  PROBE_STATE_SLEEP){
          imageStore(IrradianceAtlasImage, ivec2(gl_LaunchIDEXT.xy), vec4(0,0,0, 100.0));
          return;
       }else if (probeState == PROBE_STATE_DISABLED) {
           imageStore(IrradianceAtlasImage, ivec2(gl_LaunchIDEXT.xy), vec4(0.0, 0.0, 0.0, 0.0));
           return;
        }


}