#version 460
#extension GL_EXT_ray_tracing : require

layout(set = 0, binding = 0) uniform accelerationStructureEXT topLevelAS;
layout(set = 0, binding = 8, rgba16f) uniform image2D IrradianceAtlasImage;

layout(set = 0, binding = 9) readonly buffer StorageBuffer {
   vec4 Position[];
} SB0;

layout(set = 0, binding = 10) readonly buffer StorageBuffer2 {
   vec4 FibonacciDirections[];
} SB02;

layout (binding = 12) uniform samplerCube samplerCubeMap[2];

layout(push_constant) uniform PushConstants {
    int SkyboxIndex;    
}pc;

struct Payload {
    vec3  Color;
    float Distance;
    int Hit;
};

layout(location = 0) rayPayloadEXT Payload payload;

void main() {

 
    vec3 probeOrigin  = SB0.Position[gl_LaunchIDEXT.y].xyz;
    vec3 rayDirection = SB02.FibonacciDirections[gl_LaunchIDEXT.x].xyz;
  

   // Trace the ray
    const uint rayFlags = gl_RayFlagsOpaqueEXT;
    const uint cullMask = 0xFF;
    const float tMin = 0.001;
    const float tMax = 100.0;

   vec3 CubeMapIrradiance = texture(samplerCubeMap[pc.SkyboxIndex], rayDirection).rgb;

    traceRayEXT(topLevelAS, rayFlags, cullMask, 0, 0, 0, probeOrigin.xyz, tMin, rayDirection, tMax, 0);
     
     vec3  Radiance = payload.Color;
     float Distance = payload.Distance;

     if(payload.Hit == 0){ Radiance = CubeMapIrradiance;}
    imageStore(IrradianceAtlasImage, ivec2(gl_LaunchIDEXT.xy), vec4(Radiance,Distance));
}