#version 450

layout(binding = 0) readonly buffer StorageBuffer2 {
   vec4 FibonacciDirections[];
} SB0;

layout(binding = 1, rgba16f)  uniform image2D Radiance_Visibility;
layout(binding = 2,rgba16f)  uniform image2D  Iradiance_Visibility;

layout(push_constant) uniform PushConstants {
    int   AtlasWidthSize;  
    int   ProbeSideLength; 
    int   GutterSize;      
    int   NumRays;         
}pc;

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

//https://stackoverflow.com/questions/1730961/convert-a-2d-array-index-into-a-1d-index
//convert the current pixel into an index for the probes
int get_probe_index_from_pixels(ivec2 pixel_coords, int atlas_width, int probe_full_size) {
    
    int probes_per_row      = atlas_width  / probe_full_size; // How many probes can  be fit in one row of the atlas
    ivec2 probe_grid_coords = pixel_coords / probe_full_size; // What probe in the atlas am i in ?

    return probe_grid_coords.y * probes_per_row + probe_grid_coords.x;
}


vec2 get_probe_normalized_uv(ivec2 pixel_coords, int probe_full_size) {
    int data_size = pc.ProbeSideLength;
    
    ivec2 inner_coords = pixel_coords % probe_full_size; 
    float gutter_offset = float(pc.GutterSize) / 2.0;  

    return (vec2(inner_coords) - gutter_offset) / float(data_size - 1.0);
}

vec3 Decode(vec2 f)
{
    f = f * 2.0 - 1.0;
 
    // https://twitter.com/Stubbesaurus/status/937994790553227264
    vec3 n = vec3(f.x, f.y, 1.0 - abs(f.x) - abs(f.y));
    float t = clamp(-n.z,0.0,1.0);
    n.xy -= sign(n.xy) * t;    
    return normalize(n);
}

void main() 
{
    ivec2 index = ivec2(gl_GlobalInvocationID.xy);

    int ProbeIndex =  get_probe_index_from_pixels(index,pc.AtlasWidthSize,pc.ProbeSideLength);
    vec2 NormalisedUv = get_probe_normalized_uv(index,pc.ProbeSideLength);

    vec3 N = Decode(NormalisedUv);

    vec3  total_irradiance = vec3(0.0);
    float total_visibility = 0.0;
    float total_weight = 0.0;

    for (int ray_index = 0; ray_index <= pc.NumRays; ray_index++) {
        
        ivec2 load_coord = ivec2(ray_index, ProbeIndex);
        vec4 ray_data = imageLoad(Radiance_Visibility, load_coord);
        
        vec3 ray_radiance = ray_data.rgb;
        float ray_distance = ray_data.a;

        vec3 ray_direction = SB0.FibonacciDirections[ray_index].xyz;

        // Calculate the cosine weighting term
        float NdotL = max(0.0, dot(N, ray_direction));
        
        if (NdotL > 0.0) {
            total_irradiance += ray_radiance * NdotL;
            
            total_visibility += ray_distance * NdotL;
            
            total_weight += NdotL;
        }
    }

    vec4 final_color = vec4(0.0, 0.0, 0.0, 1000.0);

    if (total_weight > 0.0001) {
        vec3 final_irradiance = total_irradiance / total_weight;
        float final_visibility = total_visibility / total_weight; 
        
        final_color = vec4(final_irradiance, 1);
    }

    imageStore(Iradiance_Visibility, ivec2(gl_GlobalInvocationID.xy), final_color);

}
