#version 450
#extension GL_GOOGLE_include_directive : require
#include "DDGI_Include.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(binding = 0) readonly buffer StorageBuffer2 { vec4 FibonacciDirections[]; } SB0;
layout(binding = 1, rgba16f) uniform image2D Radiance_Visibility;
layout(binding = 2, rgba16f) uniform image2D Iradiance;
layout(binding = 3, rgba16f) uniform image2D Visibility;
layout(binding = 4, rgba16f) uniform image2D Prev_Iradiance;
layout(binding = 5, rgba16f) uniform image2D Prev_Visibility;

layout(push_constant) uniform PushConstants {
    int AtlasWidthSize; int ProbeSideLength; int GutterSize; int NumRays;
} pc;

struct ProbeInformation { vec4 probeLocationsXYZ_ProbeState; };

layout(set = 0,binding = 6) buffer StorageBufferObject { ProbeInformation ProbeData[]; } SBO;

shared vec3 RayDirections[256]; 

void AccumulateRay(inout vec3 irradiance, inout vec4 visibility, inout float total_weight_irrad, 
                   vec4 ray_data, float w_irrad, float w_vis) 
{   
        // Irradiance Accumulation
        if (w_irrad > 0.0001) {
            vec3 ray_radiance = ray_data.rgb * 0.95; 
            irradiance += ray_radiance * w_irrad;
            total_weight_irrad += w_irrad;
        }

        // Visibility Accumulation
        if (w_vis > 0.0001) {
            float d = min(abs(ray_data.a), 100.0);
            visibility.x += d * w_vis;
            visibility.y += (d * d) * w_vis;
            visibility.z += w_vis; 
        }
  
}

void main() 
{
    uint flat_idx = gl_LocalInvocationIndex;
    uint group_size = gl_WorkGroupSize.x * gl_WorkGroupSize.y;
    for (uint i = flat_idx; i < uint(pc.NumRays); i += group_size) {
        RayDirections[i] = SB0.FibonacciDirections[i].xyz;
    }
    barrier();

    ivec2 fragCoord = ivec2(gl_GlobalInvocationID.xy);
    int ProbeSideLength_With_Gutter = pc.ProbeSideLength + pc.GutterSize;
    int ProbeIndex = get_probe_index_from_pixels(fragCoord, pc.AtlasWidthSize, ProbeSideLength_With_Gutter);

    ProbeInformation probe = SBO.ProbeData[ProbeIndex];
    int probeState = int(probe.probeLocationsXYZ_ProbeState.w);
    
    if(probeState ==  PROBE_STATE_SLEEP){
       
       vec3 history_irradiance = imageLoad(Prev_Iradiance, fragCoord).rgb;

       imageStore(Iradiance, fragCoord, vec4(history_irradiance, 1.0));
       return;
    }




    ivec2 localPos = fragCoord % ProbeSideLength_With_Gutter;
    int probe_last_pixel = ProbeSideLength_With_Gutter - 1;

    // Identify Border Pixels
    bool border_pixel = (localPos.x == 0 || localPos.x == probe_last_pixel || 
                         localPos.y == 0 || localPos.y == probe_last_pixel);

    if (!border_pixel) {
        vec3 irradiance = vec3(0.0);
        vec4 visibility = vec4(0.0);
        float total_weight_irrad = 0.0;
        
        vec3 texel_dir = oct_decode(get_normalized_probe_texel_coord(fragCoord, pc.ProbeSideLength, pc.GutterSize));
        
        float dist_exponent = 2.5; 

        int backfaces = 0;
        int max_backfaces = int(float(pc.NumRays) * 0.1);
        
        for (int i = 0; i < pc.NumRays; i++) {
            vec4 ray_data = imageLoad(Radiance_Visibility, ivec2(i, ProbeIndex));
            
            if (ray_data.a < 0.0) {
                backfaces++;
                if (backfaces >= max_backfaces) return;
                continue; 
            }
        
            vec3 ray_dir = RayDirections[i];
            float w_irrad = max(dot(texel_dir, ray_dir), 0.0);
            float w_vis = pow(w_irrad, dist_exponent);
        
            AccumulateRay(irradiance, visibility, total_weight_irrad, ray_data, w_irrad, w_vis);
        }


        vec3 history_irradiance = imageLoad(Prev_Iradiance, fragCoord).rgb;
        vec2 history_visibility = imageLoad(Prev_Visibility, fragCoord).rg;

        vec3 result_irradiance = history_irradiance;
        vec2 result_visibility = history_visibility;

        if (total_weight_irrad > 0.00001) {

            vec3 new_irradiance = irradiance * (1.0 / (2.0 * total_weight_irrad)); 
            
            float hysteresis = 0.95;
            vec3 delta = abs(new_irradiance - history_irradiance);
            
            if (max(max(delta.r, delta.g), delta.b) > 0.2) hysteresis = 0.75; 
            
            result_irradiance = mix(new_irradiance, history_irradiance, hysteresis);
        }

        if (visibility.z > 0.00001) {
            float mean = visibility.x / visibility.z;
            float mean_sq = visibility.y / visibility.z;
            vec2 new_visibility = vec2(mean, mean_sq);
            
            float vis_hysteresis = 0.95;
            if (abs(mean - history_visibility.x) > 0.2) vis_hysteresis = 0.75;

            result_visibility = mix(new_visibility, history_visibility, vis_hysteresis);
        }

        imageStore(Iradiance, fragCoord, vec4(result_irradiance, 1.0));
        imageStore(Visibility, fragCoord, vec4(result_visibility, 1.0, 1.0));
    }

    memoryBarrierImage();
    barrier();

    // Border Pixel Copy
    if (border_pixel) {
        ivec2 sourceCoord = fragCoord;
        
        if (localPos.x == 0) sourceCoord.x += 1;
        if (localPos.x == probe_last_pixel) sourceCoord.x -= 1;
        if (localPos.y == 0) sourceCoord.y += 1;
        if (localPos.y == probe_last_pixel) sourceCoord.y -= 1;

        vec4 cop_irrad = imageLoad(Iradiance, sourceCoord);
        vec4 cop_vis   = imageLoad(Visibility, sourceCoord);
        
        imageStore(Iradiance, fragCoord, cop_irrad);
        imageStore(Visibility, fragCoord, cop_vis);
    }
}