#version 450

layout(binding = 0) readonly buffer StorageBuffer2 {
   vec4 FibonacciDirections[];
} SB0;

layout(binding = 1, rgba16f)  uniform image2D Radiance_Visibility;
layout(binding = 2, rgba16f)  uniform image2D  Iradiance;
layout(binding = 3, rgba16f)  uniform image2D  Visibility;
layout(binding = 4, rgba16f)  uniform image2D  Prev_Iradiance;
layout(binding = 5, rgba16f)  uniform image2D  Prev_Visibility;

layout(push_constant) uniform PushConstants {
    int   AtlasWidthSize;  
    int   ProbeSideLength; 
    int   GutterSize;      
    int   NumRays;
}pc;

const int PROBE_STATE_ACTIVE   = 0; //  this is for when a probe is activly collecting new scene data
const int PROBE_STATE_SLEEP    = 1; //  this is for when a probe is always hitting the skybox
const int PROBE_STATE_DISABLED = 2; //  this is for when a probe is inside an object and is not contributing meaningfully.
//A probe that is disabled can be moved so it is active

struct ProbeInformation {
    vec4 probeLocations;
    int  probeState;
    vec3 Padding;
};

layout(set = 0,binding = 6) buffer StorageBufferObject {
      ProbeInformation  ProbeData[];
}SBO;

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

//https://stackoverflow.com/questions/1730961/convert-a-2d-array-index-into-a-1d-index
//convert the current pixel into an index for the probes
int get_probe_index_from_pixels(ivec2 pixel_coords, int atlas_width, int probe_full_size) {
    
    int   probes_per_row      = atlas_width  / probe_full_size; // How many probes can  be fit in one row of the atlas
    ivec2 probe_grid_coords   = pixel_coords / probe_full_size; // What probe in the atlas am i in ?

    return probe_grid_coords.y * probes_per_row + probe_grid_coords.x; // scale it 
}


// Code adapted from:
// "Mastering Graphics Programming with Vulkan" by Packt Publishing
// GitHub repository: https://github.com/PacktPublishing/Mastering-Graphics-Programming-with-Vulkan
// Source file: source/chapter14/shaders/ddgi.glsl and source/chapter14/shaders/ddgi.h
// License: MIT License (see repository for details)

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Computes normalized texel coordinates within a single probe’s quad in the atlas.
// This just tells us where inside the probe we are, in the range [-1, +1]^2. for guttar//
vec2 get_normalized_probe_texel_coord(ivec2 fragCoord) {                                                                                               //
                                                                                                                                           //
    int probe_with_border_side  = pc.ProbeSideLength + pc.GutterSize; // How Long is a total probe?                                                      //
                                                              
       ///Where are we exactly?
    float texel_coordinatesX =   (fragCoord.x - 1) % probe_with_border_side;   
    float texel_coordinatesY =   (fragCoord.y - 1) % probe_with_border_side;  
    
    vec2 Texel = vec2(texel_coordinatesX,texel_coordinatesY);
    
    Texel += vec2(0.5f); // Adjustment so we are sampling in the middle of the pixel                                                                                            //
    Texel = (Texel / float(pc.ProbeSideLength)) * 2.0 - 1.0; // map out of texture space to normalized direction-space
                                                                                       //                                                                                                                                       //
    return Texel;                                                                                                   //                                                                                                                                         //
}                                                                                                                                          //
                                                                                                                                           //
// Returns a unit vector. Argument o is an octahedral vector packed via oct_encode,                                                        //
// on the [-1, +1] square                                                                                                                  //
float sign_not_zero(in float k) {                                                                                                          //
    return (k >= 0.0) ? 1.0 : -1.0;                                                                                                        //
}                                                                                                                                          //
                                                                                                                                           //
vec2 sign_not_zero2(in vec2 v) {                                                                                                           //
    return vec2(sign_not_zero(v.x), sign_not_zero(v.y));                                                                                   //
}                                                                                                                                          //
                                                                                                                                           //
vec3 oct_decode(vec2 o) {                                                                                                                  //
    vec3 v = vec3(o.x, o.y, 1.0 - abs(o.x) - abs(o.y));                                                                                    //
    if (v.z < 0.0) {                                                                                                                       //
        v.xy = (1.0 - abs(v.yx)) * sign_not_zero2(v.xy);                                                                                   //
    }                                                                                                                                      //
    return normalize(v);                                                                                                                   //
}                                                                                                                                          //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


#define PROCESS_RAY(ray_data, weight) \
    { \
        float ray_dist = ray_data.a; \
        RAW_RAYDISTANCE += ray_dist; \
        bool skip_arithmetic = false; \
        if (ray_dist < 0.0f && use_backfacing_blending) { \
            backfaces++; \
            if (backfaces >= max_backfaces) { \
                imageStore(Visibility, fragCoord, vec4(0,0,0,1)); \
                imageStore(Iradiance, fragCoord, vec4(0,0,0,1)); \
                return; \
            } \
            skip_arithmetic = true; \
        } \
        if (!skip_arithmetic) { \
            if (weight > 0.0001) { \
                vec3 ray_radiance = ray_data.rgb * energy_conservation; \
                irradiance += ray_radiance * weight; \
                total_weight += weight; \
                ray_dist = min(abs(ray_dist), 100.0f); \
                visibility.x += ray_dist * weight; \
                visibility.y += (ray_dist * ray_dist) * weight; \
                visibility.z += weight; \
            } \
        } \
    }




// Shared variables for workgroup
shared vec3 RayDirections[300];

void main() 
{
    //Load up all the directions
    uint flat_idx   = gl_LocalInvocationIndex; 
    uint group_size = gl_WorkGroupSize.x * gl_WorkGroupSize.y; 
    
    // Parallel load
    for (uint i = flat_idx; i < uint(pc.NumRays); i += group_size) {
        RayDirections[i] = SB0.FibonacciDirections[i].xyz;
    }
  
  barrier();



   ivec2 fragCoord = ivec2(gl_GlobalInvocationID.xy);
   const float energy_conservation = 0.95;

    int ProbeSideLength_With_Gutter  = pc.ProbeSideLength + pc.GutterSize ;
    int probe_last_pixel = pc.ProbeSideLength + (pc.GutterSize - 1); // subtract by one because the gutter is on each side

    int ProbeIndex =  get_probe_index_from_pixels(fragCoord,pc.AtlasWidthSize,ProbeSideLength_With_Gutter);

    ProbeInformation info = SBO.ProbeData[ProbeIndex];

    //if(info.probeState == PROBE_STATE_ACTIVE ){
        /// do not do any calculations on gutter pixels

    ivec2 localPos      = fragCoord % ProbeSideLength_With_Gutter;

    bool border_pixel   = (localPos.x == 0) || (localPos.x  == probe_last_pixel )||
                          (localPos.y == 0) || (localPos.y  == probe_last_pixel );

     if (border_pixel) {
        imageStore(Iradiance, fragCoord, vec4(0.0, 0.0, 0.0, 1.0));
        imageStore(Visibility, fragCoord, vec4(0.0, 0.0, 0.0, 1.0));
        return;
    }

     vec3 irradiance = vec3(0.0);
     vec4 visibility = vec4(0.0);
    float total_weight     = 0.0;
     vec4 final_color      = vec4(0.0, 0.0, 0.0, 1000.0);
     uint max_backfaces    = uint(pc.NumRays * 0.1f); // 10% of the total amount of rays being cast
     uint backfaces = 0;
     const bool use_backfacing_blending = false;
     float RAW_RAYDISTANCE = 0;
     vec3 texel_direction = oct_decode(get_normalized_probe_texel_coord(fragCoord));

     int i = 0;

     for (; i <= pc.NumRays - 4; i += 4) {
       
           vec4 ray_data0 = imageLoad(Radiance_Visibility, ivec2(i + 0, ProbeIndex));
           vec4 ray_data1 = imageLoad(Radiance_Visibility, ivec2(i + 1, ProbeIndex));
           vec4 ray_data2 = imageLoad(Radiance_Visibility, ivec2(i + 2, ProbeIndex));
           vec4 ray_data3 = imageLoad(Radiance_Visibility, ivec2(i + 3, ProbeIndex));

           vec3 ray_direction0   = RayDirections[i + 0].xyz;
           vec3 ray_direction1   = RayDirections[i + 1].xyz;
           vec3 ray_direction2   = RayDirections[i + 2].xyz;
           vec3 ray_direction3   = RayDirections[i + 3].xyz;

           float weight0 = max(dot(texel_direction, ray_direction0), 0.0); 
           float weight1 = max(dot(texel_direction, ray_direction1), 0.0); 
           float weight2 = max(dot(texel_direction, ray_direction2), 0.0); 
           float weight3 = max(dot(texel_direction, ray_direction3), 0.0); 

           PROCESS_RAY(ray_data0, weight0);
           PROCESS_RAY(ray_data1, weight1);
           PROCESS_RAY(ray_data2, weight2);
           PROCESS_RAY(ray_data3, weight3);


       }
         for (; i < pc.NumRays; i++) {
             vec4 d = imageLoad(Radiance_Visibility, ivec2(i, ProbeIndex));
             float weight = max(dot(texel_direction, RayDirections[i]), 0.0); 
             PROCESS_RAY(d, weight);
        }
     
              
    
         if (total_weight > 0.000) {
             irradiance /=  total_weight;
         
             vec3 previous_value = imageLoad( Prev_Iradiance, fragCoord).rgb;
             vec3 result         = mix(irradiance, previous_value,  0.95f);
             imageStore(Iradiance , fragCoord, vec4(result,1));
         }
          
          if (total_weight > 0.000) {
          
                // Get weighted average
               float mean     = visibility.x / visibility.z; 
               float mean_sq  = visibility.y / visibility.z;
                
               vec2 Vsibility = vec2(mean,mean_sq);
          
               vec2 previous_value = imageLoad(Prev_Visibility, fragCoord).rg;
               vec2 result         = mix( Vsibility, previous_value, 0.95f);
          
                imageStore(Visibility, fragCoord, vec4(result,RAW_RAYDISTANCE, 1.0));
            }

}
