#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_ray_query : require 
#extension GL_GOOGLE_include_directive : require
#include "PBR_Include.glsl"

layout(push_constant) uniform PushConstant{
    vec2   ScreenSize;
    int    LightCount;
    int    FrameIndex;
    vec4   GI_Solution_Index_Padding;
} PC;

struct LightData{
    vec4    positionAndLightType;
    vec4    colorAndAmbientStrength;
    vec4    CameraPositionAndLightIntensity;
};

layout(binding  = 0 ) uniform sampler2D   PositionImage;
layout(binding  = 1 ) uniform sampler2D   NormalImage;
layout(binding  = 2 ) uniform sampler2D   AlbedoImage;
layout(binding  = 3 ) uniform sampler2D   MaterialImage;
layout(binding  = 4 ) uniform samplerCube SamplerCubeMap;
layout(binding  = 5 ) uniform sampler2D   EmisiveImage;
layout(binding  = 6, rgba16f) uniform image2D OutputImage;
layout(binding  = 17, rgba32f) uniform image2D PTGI_OutputImage;

layout(set = 0, binding = 7) uniform LightUniformBuffer {
         LightData lights[1000];
};

layout(binding  = 8) uniform accelerationStructureEXT topLevelAS;

struct ShadowPayload {
       int visibility;
};

struct RTGIPayload {
       vec4 normal;
       vec4 radiance;
       vec4 position;
       vec4 albedo; 
};

layout(location = 0) rayPayloadEXT ShadowPayload shadowPayload;
layout(location = 1) rayPayloadEXT RTGIPayload   RTGIpayload;

// --- RNG ---
uint pcg_hash(uint seed) {
    uint state = seed * 747796405u + 2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

uint seed = pcg_hash(gl_LaunchIDEXT.y * gl_LaunchSizeEXT.x + gl_LaunchIDEXT.x) ^ pcg_hash(uint(PC.FrameIndex));

float rand_pcg(inout uint seed) {
    seed = pcg_hash(seed);
    return float(seed) * (1.0 / 4294967296.0);
}

vec3 GetPerpendicularVector(vec3 v) {
    return normalize(cross(v, abs(v.x) > abs(v.z) ? vec3(0.0, 0.0, 1.0) : vec3(1.0, 0.0, 0.0)));
}

vec3 GetHemisphereSample(vec2 randVal, vec3 HitNormal) {
    vec3 bitangent = GetPerpendicularVector(HitNormal);
    vec3 tangent = cross(bitangent, HitNormal);
    float r = sqrt(randVal.x);
    float phi = 2.0 * 3.14159265 * randVal.y;
    
    return tangent * (r * cos(phi)) + bitangent * (r * sin(phi)) + HitNormal.xyz * sqrt(max(0.0, 1.0 - randVal.x));
}



vec3 PathTraceGI(vec3 origin, vec3 normal) {

    vec3 accumulatedIndirect = vec3(0.0);
    vec3 throughput = vec3(1.0); 
    
    vec3 currentOrigin = origin + normal * 0.01; 
    vec3 currentNormal = normal;

    for (int bounce = 0; bounce < 5; bounce++) { 
        float rx = rand_pcg(seed);
        float ry = rand_pcg(seed);
        
        vec3 direction = GetHemisphereSample(vec2(rx, ry), currentNormal);

        RTGIpayload.radiance   = vec4(0.0);
        RTGIpayload.albedo = vec4(0.0);
        RTGIpayload.normal     = vec4(0.0); 
        RTGIpayload.position   = vec4(0.0);

        traceRayEXT(topLevelAS, gl_RayFlagsOpaqueEXT, 0xFF, 0, 0, 0, currentOrigin, 0.001, direction, 1000.0, 1);
        
        if (length(RTGIpayload.normal.xyz) < 0.1) {
             vec3 skyColor = texture(SamplerCubeMap, direction).rgb;
                accumulatedIndirect += skyColor * throughput;
          
          break;
        } 
        else {

             accumulatedIndirect += RTGIpayload.radiance.rgb * throughput;
             
             throughput *= RTGIpayload.albedo.rgb; 

             currentOrigin = RTGIpayload.position.xyz + RTGIpayload.normal.xyz * 0.001;
             currentNormal = RTGIpayload.normal.xyz;
        }
    }

    return accumulatedIndirect;
}

void main() {
   ivec2 halfCoord  = ivec2(gl_LaunchIDEXT.xy);
   ivec2 fullCoord = halfCoord;

   vec3  LightDir = vec3(1,1,1);
   const float Constant   = 1.0;
   const float Linear     = 0.09;
   const float Quadratic  = 0.032;
   vec3 radiance          = vec3(0.0);
   vec3 directLighting     = vec3(0.0);

   vec3  WorldPos       = texelFetch(PositionImage,fullCoord,0).rgb;
   vec3  Normal         = normalize(texelFetch(NormalImage,fullCoord,0).rgb);
   vec3  Albedo         = texelFetch(AlbedoImage,fullCoord,0).rgb;
   float Metallic       = texelFetch(MaterialImage,fullCoord,0).r;
   float Roughness      = texelFetch(MaterialImage,fullCoord,0).g;
   vec3  Emmisive       = texelFetch(EmisiveImage,fullCoord,0).rgb;

   vec3  ViewDir    = normalize(lights[0].CameraPositionAndLightIntensity.xyz -  WorldPos);

   if (dot(Normal, ViewDir) < 0.0) {
    Normal = -Normal;
}

   const float tMin = 0.001;
   vec3 F0 = mix(vec3(0.04), Albedo, Metallic);
   vec3 shadowOrigin = WorldPos + (Normal * 0.04);

   for (int i = 0; i < PC.LightCount; i++) {
        LightData light = lights[i];
        vec3 Lo       = vec3(0.0);
        float tMax = 10000.0;

        if(light.positionAndLightType.w < 0.5){
             LightDir = normalize(-light.positionAndLightType.xyz);
             radiance = light.colorAndAmbientStrength.rgb;
             tMax = 1000.0;
        }
        else if (light.positionAndLightType.w > 0.5){
             vec3 LightPos    = light.positionAndLightType.xyz;
             LightDir     = normalize(LightPos - WorldPos);
             float Distance     = length(LightPos -  WorldPos);
             float Attenuation = 1.0 / (Constant + Linear * Distance + Quadratic * (Distance * Distance));
             radiance     = light.colorAndAmbientStrength.rgb * Attenuation;
             tMax         = Distance;
        }  

        float NdotL = max(dot(Normal, LightDir), 0.0);         

        vec3 halfwayDir  = normalize(LightDir + ViewDir);
        float HdotV  = max(dot(halfwayDir, ViewDir), 0.0);

        vec3 F    = fresnelSchlick(HdotV, F0);
        float NDF = DistributionGGX(Normal, halfwayDir, Roughness);      
        float G   = GeometrySmith(Normal, ViewDir, LightDir, Roughness);

        vec3  numerator     = NDF * G * F;
        float denominator  = 4.0 * max(dot(Normal, ViewDir), 0.0) * max(dot(Normal, LightDir), 0.0)  + 0.0001;
        vec3  specular      = (numerator / denominator);
   
        vec3 kS = F;
        vec3 kD = vec3(1.0) - kS;
        kD *= 1.0 - Metallic;
   
        vec3 diffuse = kD * (Albedo / PI);

        Lo += (diffuse + specular) * radiance * NdotL;

        float r1 = rand_pcg(seed);
        float r2 = rand_pcg(seed);
        float radius = 0.25; 

        vec3 softLightDir;


       //f(light.positionAndLightType.w < 0.5) {
       //  radius = 0.009; 
       //  softLightDir = DirectionalSoftShadow(LightDir, radius, r1, r2);
       // } else {
       //   softLightDir = SoftShadow(light.positionAndLightType.xyz, WorldPos, radius, r1, r2);
       // }


        shadowPayload.visibility = 0; 

            traceRayEXT(
               topLevelAS, 
               gl_RayFlagsTerminateOnFirstHitEXT | gl_RayFlagsOpaqueEXT | gl_RayFlagsSkipClosestHitShaderEXT, 
               0xFF, 
               0, 0, 0, 
               shadowOrigin, 
               0.001, 
               LightDir, 
               tMax, 
               0 
            );
        
        directLighting += Lo * lights[i].CameraPositionAndLightIntensity.a * float(shadowPayload.visibility);
    }

    vec3 indirectLighting = vec3(0);

    if(PC.GI_Solution_Index_Padding.x == 1){ 
        indirectLighting = PathTraceGI(WorldPos, Normal) * Albedo;    
    }

    //vec3 reflectionLighting = vec3(0.0);
    //if (Roughness < 1.0) {
    //    vec3 refDir = reflect(-ViewDir, Normal);
    //    
    //    RTGIpayload.radiance = vec4(0.0);
    //    RTGIpayload.normal = vec4(0.0);
    //    
    //    traceRayEXT(topLevelAS, gl_RayFlagsOpaqueEXT, 0xFF, 0, 0, 0, 
    //                WorldPos + Normal * 0.001, 0.03, refDir, 100.0, 1);
    //    
    //    if (length(RTGIpayload.normal.xyz) < 0.1) {
    //        reflectionLighting = texture(SamplerCubeMap, refDir).rgb;
    //    } else {
    //        reflectionLighting = RTGIpayload.radiance.rgb;
    //    }
    //    
    //    vec3 F_reflect = fresnelSchlick(max(dot(Normal, ViewDir), 0.0), F0);
    //    reflectionLighting *= F_reflect * (1.0 - Roughness);
    //}

    //imageStore(OutputImage     , fullCoord, vec4(directLighting + Emmisive + reflectionLighting, 1.0));
    imageStore(OutputImage     , fullCoord, vec4(directLighting + Emmisive, 1.0));
    imageStore(PTGI_OutputImage, fullCoord, vec4(indirectLighting, 1.0));
}

//
//void main() {
//    ivec2 fullCoord = ivec2(gl_LaunchIDEXT.xy);
//
//    vec3 TargetWorldPos = texelFetch(PositionImage, fullCoord, 0).rgb;
//    
//    vec3 CameraPos = lights[0].CameraPositionAndLightIntensity.xyz;
//
//    vec3 direction = normalize(TargetWorldPos - CameraPos);
//
//    RTGIpayload.radiance = vec4(0.0);
//    RTGIpayload.albedo   = vec4(1.0, 0.0, 0.0, 1.0); 
//    RTGIpayload.normal   = vec4(0.0);
//    RTGIpayload.position = vec4(0.0);
//
//    traceRayEXT(
//        topLevelAS, 
//        gl_RayFlagsOpaqueEXT, 
//        0xFF, 
//        0, 0, 0, 
//        CameraPos,    // Origin
//        0.001,        // tMin
//        direction,    // Direction
//        10000.0,      // tMax
//        1             // Payload Location 1 (RTGIPayload)
//    );
//
//    imageStore(OutputImage, fullCoord, vec4(RTGIpayload.normal.rgb, 1.0));
//}