#version 450
#extension GL_GOOGLE_include_directive : require
#include "DDGI_Include.glsl"

layout(binding = 1, rgba16f)  uniform image2D  Iradiance;
layout(binding = 2, rgba16f)  uniform image2D  Visibility;
layout(binding = 3, rgba16f)  uniform image2D  Radiance_Visibility;

layout(push_constant) uniform PushConstants {
    int   AtlasWidthSize;  
    int   ProbeSideLength; 
    int   GutterSize;      
    int   NumRays;
}pc;


//A probe that is disabled can be moved so it is active

struct ProbeInformation {
      vec4 probeLocationsXYZ_ProbeState;
};

layout(set = 0,binding = 0) buffer StorageBufferObject {
      ProbeInformation  ProbeData[];
}SBO;

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

void main() 
{
   
    if (gl_LocalInvocationIndex == 0) {
        
        int ProbeSideLength_With_Gutter = pc.ProbeSideLength + pc.GutterSize;

        // Find out which probe this 8x8 group is working on
        int probeIndex = get_probe_index_from_pixels(ivec2(gl_WorkGroupID.xy * 8), pc.AtlasWidthSize,ProbeSideLength_With_Gutter);

        // Check buffer bounds
        int numProbes = SBO.ProbeData.length();
        if (probeIndex >= numProbes) {
            return;
        }


        int skyHits = 0;
        int insideHits = 0;

        const float SkyDistance    = 1000.0;
        const float Inside         = 0.1;

        // Get the raw Distance traveled of the ray 
        for (int RayIndex = 0; RayIndex < pc.NumRays; RayIndex++) {
            
            ivec2 TexCoord = ivec2(RayIndex, probeIndex);
           
            float Distance = imageLoad(Radiance_Visibility, TexCoord).a;

            if (Distance > SkyDistance) {
                skyHits++;
            }
            else if (Distance < Inside) {
                insideHits++;
            }
        }

        float SkyPercent    = float(skyHits)    / float(pc.NumRays);
        float InsidePercent = float(insideHits) / float(pc.NumRays);

        const float SLEEP_THRESHOLD    = 0.95; 
        const float DISABLE_THRESHOLD  = 0.90; 

        const float WAKE_THRESHOLD     = 0.85; 
        const float ENABLE_THRESHOLD   = 0.80; 

        ProbeInformation probe = SBO.ProbeData[probeIndex];

        int ProbeState =  int(probe.probeLocationsXYZ_ProbeState.w);

        int currentState = ProbeState;

        if (currentState == PROBE_STATE_ACTIVE) {

            if (SkyPercent > SLEEP_THRESHOLD) {

                ProbeState = PROBE_STATE_SLEEP;

            } else if (InsidePercent > DISABLE_THRESHOLD) {

                ProbeState = PROBE_STATE_DISABLED;

            }

        } 
        else if (currentState == PROBE_STATE_SLEEP) {

            if (SkyPercent < WAKE_THRESHOLD) { 

                ProbeState = PROBE_STATE_ACTIVE;

            }
        } 
        else if (currentState == PROBE_STATE_DISABLED) {

            if (InsidePercent < ENABLE_THRESHOLD) {

                  ProbeState = PROBE_STATE_ACTIVE;

            }
        }

        SBO.ProbeData[probeIndex] = probe;
    }
}
