#version 460
#extension GL_EXT_ray_tracing : require

layout(set = 0, binding = 0) uniform accelerationStructureEXT topLevelAS;
layout(set = 0, binding = 4, rgba16f) uniform image2D OutputImage;

layout(set = 0, binding = 5) uniform Camera {
    mat4 inverseViewMatrix;
    mat4 inverseProjectionMatrix;
} cam;

struct Payload {
    vec3 Color;
    float Distance;
    vec3 Normal;
};

layout(location = 0) rayPayloadEXT Payload payload;

void main() {
    vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
    vec2 uv = pixelCenter / vec2(gl_LaunchSizeEXT.xy);
    vec2 ndc = uv * 2.0 - 1.0;

    vec4 rayOrigin = cam.inverseViewMatrix * vec4(0,0,0,1);
    vec4 target = cam.inverseProjectionMatrix * vec4(ndc.x, ndc.y, 1, 1);
    vec3 rayDir = normalize((cam.inverseViewMatrix * vec4(target.xyz / target.w, 0)).xyz);

    // Trace the ray
    const uint rayFlags = gl_RayFlagsOpaqueEXT;
    const uint cullMask = 0xFF;
    const float tMin = 0.001;
    const float tMax = 100000.0;

     

    traceRayEXT(topLevelAS, rayFlags, cullMask, 0, 0, 0, rayOrigin.xyz, tMin, rayDir, tMax, 0);
      payload.Color = vec3(0);

      vec3 ReflectionColor = vec3(0);

    if (payload.Distance > 0.0f) {
   
		const vec3 hitPos = rayOrigin.xyz + rayDir * payload.Distance;
		rayOrigin.xyz = hitPos.xyz + payload.Normal * 0.001f;
		rayDir.xyz = reflect(rayDir.xyz, payload.Normal);
        
        traceRayEXT(topLevelAS, rayFlags, cullMask, 0, 0, 0, rayOrigin.xyz, tMin, rayDir, tMax, 0);
   
        ReflectionColor = payload.Color;
    }

    imageStore(OutputImage, ivec2(gl_LaunchIDEXT.xy), vec4(ReflectionColor, 1.0));
}