#version 450

struct LightData{
    vec4    positionAndLightType;
    vec4    colorAndAmbientStrength;
    vec4    CameraPositionAndLightIntensity;
};

layout(binding = 0) uniform LightUniformBuffer {
      LightData lights[100];
};

layout(binding = 1, rgba16f)  uniform image2D ResevoirImage;
layout(binding = 2)  uniform sampler2D WorldPositionImage;
layout(binding = 3)  uniform sampler2D NormalImage;
layout(binding = 4)  uniform sampler2D AlbedoImage;
layout(binding = 5)  uniform sampler2D MaterialImage;
layout (binding = 6) uniform sampler2D BlueNoise[63];

layout(push_constant) uniform PushConstant{
      vec4 CameraPosition;
      vec4 ScreenSize_Padding_FrameIndex;
}PC;


layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

const float PI = 3.14159265359;
const float Constant  = 1.0;
const float Linear    = 0.09;
const float Quadratic = 0.032;

struct SurfaceData {
    vec3  worldPos;
    vec3  normal;
    vec3  albedo;
    float metallic;
    float roughness;
};

struct Reservoir
{
    uint Y; // index of most important light
    float W_y; // light weight
    float W_sum; // sum of all weights for all lights processed
    float M; // number of lights processed for this reservoir
};

vec3 GetPointLightRadiance(LightData light, vec3 cameraPos, SurfaceData surface)
{
    vec3 radiance = vec3(0.0);
    vec3 LightDir = vec3(0.0);

    if (light.positionAndLightType.w > 0.5)
    {
        vec3  LightPos  = light.positionAndLightType.xyz;
        LightDir        = normalize(LightPos - surface.worldPos);
        float Distance    = length(LightPos - surface.worldPos);
        float Attenuation = 1.0 / (Constant + Linear * Distance + Quadratic * (Distance * Distance));
        radiance        = light.colorAndAmbientStrength.rgb * Attenuation;
    }
    else 
    {
        LightDir = normalize(-light.positionAndLightType.xyz);
        radiance = light.colorAndAmbientStrength.rgb;
    }

 

    float NdotL = max(dot(surface.normal, LightDir), 0.0);
    
    float lightIntensity = light.CameraPositionAndLightIntensity.a;
    
   vec3 approxRadiance = (surface.albedo / PI) * radiance * NdotL * lightIntensity;
   return approxRadiance;
}

 
float hash13(vec3 p) {
    p = fract(p * 0.1031);
    p += dot(p, p.yzx + 33.33);
    return fract((p.x + p.y) * p.z);
}


bool UpdateReservoir(inout Reservoir reservoir, uint X, float w, float c, vec2 seed)
{
    reservoir.W_sum += w;
    reservoir.M += c;
        ivec2 TextCoord = ivec2(gl_GlobalInvocationID.xy);
     vec2 uv = (vec2(TextCoord) + 0.5) / PC.ScreenSize_Padding_FrameIndex.xy;
     vec2 tiledUV = fract(uv * 64.0);  

    // better random
   float noise = textureLod(BlueNoise[int(PC.ScreenSize_Padding_FrameIndex.z)], tiledUV,0).r;

    if (noise < w / reservoir.W_sum)
    {
        reservoir.Y = X;
        return true;
    }
    return false;
}


void main() 
{
    ivec2 TextCoord = ivec2(gl_GlobalInvocationID.xy);

    SurfaceData surfaceData;

    surfaceData.worldPos = texelFetch(WorldPositionImage,TextCoord,0).xyz;

    if (surfaceData.worldPos == vec3(0.0))
    {
        imageStore(ResevoirImage, TextCoord, vec4(0.0));
        return; 
    }

    surfaceData.normal    = texelFetch(NormalImage  ,TextCoord,0).xyz;
    surfaceData.albedo    = texelFetch(AlbedoImage  ,TextCoord,0).xyz;
    surfaceData.metallic  = texelFetch(MaterialImage,TextCoord,0).x;
    surfaceData.roughness = texelFetch(MaterialImage,TextCoord,0).y;
       
    vec3  CameraPos = PC.CameraPosition.xyz;

    Reservoir reservoir;
              reservoir.Y = 0;
              reservoir.W_y = 0.0;
              reservoir.W_sum = 0.0;
              reservoir.M = 0.0;

    int TotalNumOfLights = 50;
    int NoofPoint = 16; 

    float pdf = 1.0 / float(TotalNumOfLights); 
    float p_hat = 0;

     vec2 uv = (vec2(TextCoord) + 0.5) / vec2(128);
     vec2 tiledUV = fract(uv);  


for (uint i = 0; i < NoofPoint; i++)
{
    float frame = float(PC.ScreenSize_Padding_FrameIndex.z);


   float noise = textureLod(BlueNoise[int(PC.ScreenSize_Padding_FrameIndex.z)], tiledUV,0).r;

    uint lightIndex = uint(noise* float(TotalNumOfLights));
    lightIndex = min(lightIndex, uint(TotalNumOfLights - 1));

    p_hat = length(GetPointLightRadiance(lights[lightIndex], CameraPos, surfaceData));
    float w = p_hat / pdf;

    UpdateReservoir(reservoir, lightIndex, w, 1.0, vec2(noise, frame));
}

    p_hat = 0.0; 

    if (reservoir.M > 0.0 && reservoir.W_sum > 0.0)
    {
        p_hat = length(GetPointLightRadiance(lights[reservoir.Y], CameraPos, surfaceData));
        

        reservoir.W_y = (p_hat > 0.0) ? (1.0 / p_hat) * reservoir.W_sum / reservoir.M : 0.0;
    }
    else
    {
        reservoir.Y = 0;
        reservoir.W_y = 0.0;
        reservoir.W_sum = 0.0;
        reservoir.M = 0.0;
    }

    vec4 reservoirData = vec4(
                           float(reservoir.Y),
                           reservoir.W_y,     
                           reservoir.W_sum,   
                           reservoir.M);      

    imageStore(ResevoirImage, TextCoord, reservoirData);
}