#version 460
#extension GL_EXT_ray_tracing : require

// Adapted from the NVIDIA ReSTIR DI Paper (Bitterli et al. 2020)
// References: 
// 1. Blog: https://interplayoflight.wordpress.com/2023/12/17/a-gentler-introduction-to-restir/
// 2. Course: https://intro-to-restir.cwyman.org/

struct LightData{
    vec4    positionAndLightType;
    vec4    colorAndAmbientStrength;
    vec4    CameraPositionAndLightIntensity;
};

layout(binding = 0) uniform LightUniformBuffer {
      LightData lights[100];
};

layout(binding = 1, rgba16f)  uniform image2D ResevoirImage;
layout(binding = 2)  uniform sampler2D WorldPositionImage;
layout(binding = 3)  uniform sampler2D NormalImage;
layout(binding = 4)  uniform sampler2D AlbedoImage;
layout(binding = 5)  uniform sampler2D MaterialImage;
layout (binding = 6) uniform sampler2D BlueNoise[63];
layout(set = 0, binding = 7) uniform accelerationStructureEXT topLevelAS;
layout (binding = 16, rgba16f) uniform image2D PrevResevoirImage;
layout (binding = 17) uniform sampler2D MotionVectorImage;
layout (binding = 18, rgba16f) uniform image2D ReSTIR_DIImage;
layout (binding = 19) uniform sampler2D PrevNormalImage;
layout(set = 1, binding = 0,rgba16f) uniform readonly image2D  IrradianceStorageImage;
layout(set = 1, binding = 1,rgba16f) uniform readonly image2D  VisibilityStorageImage;

layout(push_constant) uniform PushConstant{
    vec4 CameraPosition;
    vec4 ScreenSize_Padding_FrameIndex_LightCount;

    vec4 GridBaseLocation_ScreenSizeWidth;
    vec4 ProbeSpacing_ScreenSizeHeight;
    vec4 ProbeCount;

    ///////////////////////

    int   AtlasWidthSize;  
    int   ProbeSideLength; 
    int   GutterSize;      
    int   NumRays;
    vec4 TemporalReuse_SpatialReuse_ReSTIRwithDDGI_Padding_Flag;

}pc;

const int GIIndex = 200;

const float PI = 3.14159265359;
const float Constant  = 1.0;
const float Linear    = 0.09;
const float Quadratic = 0.032;

float sign_not_zero(in float k) {
    return (k >= 0.0) ? 1.0 : -1.0;
}

vec2 sign_not_zero2(in vec2 v) {
    return vec2(sign_not_zero(v.x), sign_not_zero(v.y));
}

vec2 oct_encode(in vec3 v) {
    float l1norm = abs(v.x) + abs(v.y) + abs(v.z);
    vec2 result = v.xy * (1.0 / l1norm);
    if (v.z < 0.0) {
        result = (1.0 - abs(result.yx)) * sign_not_zero2(result.xy);
    }
    return result;
}

ivec2 GetProbeTexel(vec2 uv, ivec3 probeIndex)
{

    int probe_full_size = pc.ProbeSideLength + pc.GutterSize;
    int probes_per_row  = pc.AtlasWidthSize / probe_full_size;

    // Flatten 3D probe index to 1D
    int linear_index = probeIndex.x + probeIndex.y * int(pc.ProbeCount.x) + probeIndex.z * int(pc.ProbeCount.x * pc.ProbeCount.y);

    // Top-left corner of this probe in the atlas
    ivec2 probe_origin = ivec2((linear_index % probes_per_row) * probe_full_size,
                               (linear_index / probes_per_row) * probe_full_size);

    // Compute texel offset inside the probe region 
    ivec2 border_offset = ivec2(pc.GutterSize / 2);

    vec2 pixel_pos      = uv * float(pc.ProbeSideLength);
    
    ivec2 pixel_offset = clamp(ivec2(pixel_pos), ivec2(0), ivec2(pc.ProbeSideLength - 1));

    return probe_origin + (border_offset + pixel_offset);
}

vec3 SampleIrradiance( vec3 Position, vec3 Normal)
{

    vec3  GridBaseLocation = pc.GridBaseLocation_ScreenSizeWidth.xyz;
    vec3  ProbeSpacing     = pc.ProbeSpacing_ScreenSizeHeight.xyz;
    ivec3 ProbeCount       = ivec3(pc.ProbeCount.xyz);

 
 
    float push_bias = 0.1; 
    vec3 SamplePosition = Position + Normal * push_bias;

    vec3 GridIndexF = ((SamplePosition ) - GridBaseLocation) / ProbeSpacing;
    vec3 Alpha = fract(GridIndexF);

    ivec3 GridIndex = ivec3(GridIndexF);

     ivec3 Offsets[8] = {
         ivec3(0,0,0), ivec3(1,0,0),
         ivec3(0,1,0), ivec3(1,1,0),
         ivec3(0,0,1), ivec3(1,0,1),
         ivec3(0,1,1), ivec3(1,1,1)
     };



     vec4 Irradiance       = vec4(0);
     vec4 IrradianceNoCheb = vec4(0);

         // Encode direction into [0,1] texture space
    vec2 Normaluv = (oct_encode(normalize(Normal)) * 0.5) + 0.5;

     for(int i = 0; i < 8; i++){

         ivec3 Offset = ivec3(i, i >> 1, i >> 2) & ivec3(1);
         ivec3 ProbeIndex         = clamp((GridIndex + Offsets[i]),ivec3(0),ProbeCount - 1);
         vec3  ProbeWorldPosition = GridBaseLocation + (vec3(ProbeIndex) * ProbeSpacing);

         ivec2 irradiance_texel = GetProbeTexel(Normaluv,ProbeIndex);

         vec3 dir = SamplePosition  -  ProbeWorldPosition ;
         float r = length(dir);
         dir *= -1.0 / r;

         ////////////////////////////////////////////////////////
         float weight = (dot(dir, Normal) + 1) * 0.5;
               weight = (weight * weight);

         float weightNoCheb = (dot(dir, Normal) + 1) * 0.5;
               weightNoCheb = (weightNoCheb * weightNoCheb) + 0.2;
         ////////////////////////////////////////////////////////


        vec3 CornerWeight = mix(vec3(1.0) - Alpha, Alpha, vec3(Offset));
        float TrilinearWeight = CornerWeight.x * CornerWeight.y * CornerWeight.z;
                if (TrilinearWeight <= 0.0001) continue;

          ///////////////////////////////////////////
          weight       *= (TrilinearWeight + 0.001f);
          weightNoCheb *= (TrilinearWeight + 0.001f);

          //////////////////////////////////////////////////////////////
          vec2  Diruv = (oct_encode(normalize(dir)) * 0.5) + 0.5;
          ivec2 visibility_texel = GetProbeTexel(Diruv, ProbeIndex);
          vec2 DepthInfo =  imageLoad(VisibilityStorageImage, visibility_texel).rg;

          float Mean  = DepthInfo.x; 
          float Mean2 = DepthInfo.y; 
         
         ///////Same as how shadow maps are calculated
         float chebyshev_weight = 1.0;

         float bias = 0.1; // 
         float r_biased = r - 0.05 ;  

         if(r_biased >  Mean) {
         
             float variance = abs((Mean * Mean) - Mean2);
             const float distanceDiff = r - Mean;
             chebyshev_weight = variance / (variance + (distanceDiff * distanceDiff));
             weight *= chebyshev_weight;
          }


         vec3 probeIrradiance = sqrt(imageLoad(IrradianceStorageImage, irradiance_texel).rgb);
         IrradianceNoCheb += vec4(probeIrradiance * weightNoCheb, weightNoCheb);
         Irradiance       += vec4(probeIrradiance * weight, weight);
     }
     
       vec3 ComputedIrradiance       = (Irradiance.rgb       * (1.0 / Irradiance.a));
       vec3 ComputedIrradianceNoCheb = (IrradianceNoCheb.rgb * (1.0 / IrradianceNoCheb.a));

       ComputedIrradiance       = ComputedIrradiance * ComputedIrradiance;
       ComputedIrradianceNoCheb = ComputedIrradianceNoCheb * ComputedIrradianceNoCheb;
       
       vec3   Result =  mix(ComputedIrradianceNoCheb,ComputedIrradiance,clamp(IrradianceNoCheb.a,0,1));
       return Result;
}

uint pcg_hash(uint seed)
{
    uint state = seed * 747796405u + 2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

float rand01(inout uint seed) {
    seed = pcg_hash(seed);
    return float(seed) / float(0xFFFFFFFFu);
}

vec3 fresnelSchlick(float cosTheta, vec3 F0)
{
    return F0 + (1.0 - F0) * pow(clamp(1.0 - cosTheta, 0.0, 1.0), 5.0);
}  

float DistributionGGX(vec3 N, vec3 H, float roughness)
{
    float safeRoughness = max(roughness, 0.05);
    float a      = safeRoughness*safeRoughness;
    float a2     = a*a;
    float NdotH  = max(dot(N, H), 0.0);
    float NdotH2 = NdotH*NdotH;
    
    float num   = a2;
    float denom = (NdotH2 * (a2 - 1.0) + 1.0);
    denom = PI * denom * denom;
    
    return num / denom;
}

float GeometrySchlickGGX(float NdotV, float roughness)
{
    float r = (roughness + 1.0);
    float k = (r*r) / 8.0;

    float num   = NdotV;
    float denom = NdotV * (1.0 - k) + k;
    
    return num / denom;
}
float GeometrySmith(vec3 N, vec3 V, vec3 L, float roughness)
{
    float NdotV = max(dot(N, V), 0.0);
    float NdotL = max(dot(N, L), 0.0);
    float ggx2  = GeometrySchlickGGX(NdotV, roughness);
    float ggx1  = GeometrySchlickGGX(NdotL, roughness);
    
    return ggx1 * ggx2;
}

struct SurfaceData {
    vec3  worldPos;
    vec3  normal;
    vec3  albedo;
    float metallic;
    float roughness;
};

struct UnifiedPayload {
    int  rayType; 
    vec3 data;   
    vec3 Emissive;

    vec3 Position;
    vec3 Normal;
    vec3 Albedo;

};

layout(location = 0) rayPayloadEXT UnifiedPayload payload;

bool TraceShadow(vec3 origin, vec3 direction, float MaxDistance) {
    payload.rayType = 0;
    payload.data.x = 1.0;

    const uint rayFlags = gl_RayFlagsOpaqueEXT | 
                           gl_RayFlagsTerminateOnFirstHitEXT | 
                          gl_RayFlagsCullBackFacingTrianglesEXT;

    const uint cullMask = 0xFF;
    const float tMin = 0.1;
    const float tMax = MaxDistance;

    traceRayEXT(
        topLevelAS,
        rayFlags,
        cullMask,
        0, 0, 0,
        origin,
        tMin,
        direction,
        tMax,
        0
    );

    return payload.data.x > 0.5;
}

vec3 offsetPositionAlongNormal(vec3 ViewPosition, vec3 normal)
{
    return ViewPosition + 0.06 * normal;
}

struct Reservoir
{
    uint  Light_Index; 
    float Light_Weight; 
    float Sum_Of_All_Weights; 
    float Num_OF_Lights_In_Resevoir; 
};

vec3 GetLightRadiance(LightData light, vec3 cameraPos, SurfaceData surface, vec3 ViewDir, vec3 F, vec3 diffuse)
{
    vec3  worldPos  = surface.worldPos;
    vec3  normal    = surface.normal;
    vec3  albedo    = surface.albedo;
    float metallic  = surface.metallic;
    float roughness = surface.roughness;
      
    vec3 radiance = vec3(0.0);
    vec3 LightDir = vec3(0.0);
    vec3 Lo       = vec3(0.0);

    if (light.positionAndLightType.w > 0.5)
    {
        vec3  LightPos    = light.positionAndLightType.xyz;
              LightDir    = normalize(LightPos - worldPos);
        float Distance    = length(LightPos - worldPos);
        float Attenuation = 1.0 / (Constant + Linear * Distance + Quadratic * (Distance * Distance));
              radiance    = light.colorAndAmbientStrength.rgb * Attenuation;
    }
    else 
    {
        LightDir = normalize(-light.positionAndLightType.xyz);
        radiance = light.colorAndAmbientStrength.rgb;
    }

    vec3 halfwayDir  = normalize(LightDir + ViewDir);

    float NDF   = DistributionGGX(normal, halfwayDir, roughness);     
    float G     = GeometrySmith(normal, ViewDir, LightDir, roughness);

    vec3  numerator     = NDF * G * F;
    float denominator  = 4.0 * max(dot(surface.normal, ViewDir), 0.0) * max(dot(normal, LightDir), 0.0)  + 0.0001;
    vec3  specular     = (numerator / denominator);


    float NdotL = max(dot(normal, LightDir), 0.0);
            Lo += (diffuse + specular) * radiance * NdotL;

    float lightIntensity = light.CameraPositionAndLightIntensity.a;
    
   vec3 Radiance = Lo * lightIntensity;

   return Radiance;
}


bool UpdateReservoir(inout Reservoir reservoir, uint LightIndex, float Weight, float c, inout uint seed)
{
    //accumilate data
    reservoir.Sum_Of_All_Weights += Weight;
    reservoir.Num_OF_Lights_In_Resevoir += c;

    if (rand01(seed) < (Weight / reservoir.Sum_Of_All_Weights))
    {
        reservoir.Light_Index = LightIndex;
        return true;
    }

    return false;
}

vec3 GetPerpendicularVector(vec3 v) {
    return normalize(cross(v, abs(v.x) > abs(v.z) ? vec3(0.0, 0.0, 1.0) : vec3(1.0, 0.0, 0.0)));
}

vec3 GetHemisphereSample(vec2 randVal, vec3 HitNormal) {
    vec3 bitangent = GetPerpendicularVector(HitNormal);
    vec3 tangent = cross(bitangent, HitNormal);
    float r = sqrt(randVal.x);
    float phi = 2.0 * 3.14159265 * randVal.y;
    
    return tangent * (r * cos(phi)) + bitangent * (r * sin(phi)) + HitNormal.xyz * sqrt(max(0.0, 1.0 - randVal.x));
}

vec3 GetRadiance(uint lightIndex, vec3 cameraPos, SurfaceData surface, vec3 ViewDir, vec3 F, vec3 diffuse, vec3 IndirectRadiance)
{
    if (lightIndex == GIIndex) {
        return IndirectRadiance;
    }

    return GetLightRadiance(lights[lightIndex], cameraPos, surface, ViewDir, F, diffuse);
}


void main() {

    ivec2 TextCoord = ivec2(gl_LaunchIDEXT.xy + 0.5);
    uint rngState = uint(TextCoord.x) + uint(TextCoord.y) * 528u + uint(pc.ScreenSize_Padding_FrameIndex_LightCount.z) * 1920u;
    

    SurfaceData surfaceData;
    surfaceData.worldPos = texelFetch(WorldPositionImage, TextCoord, 0).xyz;

    if (surfaceData.worldPos == vec3(0.0)) {
        imageStore(ResevoirImage, TextCoord, vec4(0.0));
        imageStore(ReSTIR_DIImage, TextCoord, vec4(0.0));
        return; 
    }

    surfaceData.normal    = texelFetch(NormalImage, TextCoord, 0).xyz;
    surfaceData.albedo    = texelFetch(AlbedoImage, TextCoord, 0).xyz;
    vec2 material         = texelFetch(MaterialImage, TextCoord, 0).xy;
    surfaceData.metallic  = material.x;
    surfaceData.roughness = material.y; 
   
    vec3 CameraPos = pc.CameraPosition.xyz;
    vec3 ViewDir   = normalize(CameraPos - surfaceData.worldPos);
    vec3 F0        = mix(vec3(0.04), surfaceData.albedo, surfaceData.metallic);
    vec3 F         = fresnelSchlick(max(dot(surfaceData.normal, ViewDir), 0.0), F0);
    vec3 diffuse   = (vec3(1.0) - F) * (1.0 - surfaceData.metallic) * (surfaceData.albedo / PI);
    vec3 rayOrigin = offsetPositionAlongNormal(surfaceData.worldPos, surfaceData.normal);


   vec2 uv = (vec2(TextCoord) + 0.5) / vec2(128,128);
    int DiffuseRandIndex = int(pc.ScreenSize_Padding_FrameIndex_LightCount.z - 3) % 63;
    vec3 DiffuseDirection = GetHemisphereSample(textureLod(BlueNoise[DiffuseRandIndex], uv, 0).rg, surfaceData.normal);


    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    Reservoir currentReservoir;
    currentReservoir.Light_Index = 0;
    currentReservoir.Light_Weight = 0.0;
    currentReservoir.Sum_Of_All_Weights = 0.0;
    currentReservoir.Num_OF_Lights_In_Resevoir = 0.0;

    int TotalNumOfLights = int(pc.ScreenSize_Padding_FrameIndex_LightCount.w);
    float pdf = 1.0 / float(TotalNumOfLights); 
    float p_hat_current = 0.0; 

    for (uint i = 0; i < 9; i++) {  
        uint lightIndex = min(uint(rand01(rngState) * float(TotalNumOfLights)), uint(TotalNumOfLights - 1)); 
        vec3 RadianceCandidate = GetLightRadiance(lights[lightIndex], CameraPos, surfaceData, ViewDir, F, diffuse);  
        float p_hat = length(RadianceCandidate);
        float WeightOfLight = p_hat / pdf; 

        if(UpdateReservoir(currentReservoir, lightIndex, WeightOfLight, 1.0, rngState)){
            p_hat_current = p_hat;
        }
    }


vec3 IndirectRadiance = vec3(0.0);

    if (pc.TemporalReuse_SpatialReuse_ReSTIRwithDDGI_Padding_Flag.z > 0.5) {
        payload.rayType = 1;
        payload.data = vec3(0.0);
        payload.Emissive = vec3(0.0);
        
        traceRayEXT(topLevelAS, gl_RayFlagsOpaqueEXT | gl_RayFlagsTerminateOnFirstHitEXT | gl_RayFlagsCullBackFacingTrianglesEXT, 0xFF, 0, 0, 0, rayOrigin, 0.1, DiffuseDirection, 1000.0, 0);

        vec3 HitIrradiance       = SampleIrradiance(payload.Position.xyz, payload.Normal.xyz);
    
        vec3 ResultingIrradiance = HitIrradiance * (payload.Albedo / PI);

        vec3 HitEmissive         = payload.Emissive;
        
        vec3 TotalIncomingLight  = HitEmissive + HitReflected;
       
        IndirectRadiance         = TotalIncomingLight * surfaceData.albedo;

        float GI_p_hat = length(IndirectRadiance);
        float WeightOfGI = GI_p_hat  * float(TotalNumOfLights);

        if(UpdateReservoir(currentReservoir, GIIndex, WeightOfGI, 1.0, rngState)){
            p_hat_current = GI_p_hat;
        }
    }
   

    if (p_hat_current > 0.0) {    
        currentReservoir.Light_Weight = (1.0 / p_hat_current) * (currentReservoir.Sum_Of_All_Weights / currentReservoir.Num_OF_Lights_In_Resevoir);
    } else {
        currentReservoir.Light_Weight = 0.0;
    }

        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


    //TEMPORAL REUSE
    Reservoir temporalReservoir;
    temporalReservoir.Light_Index = 0;
    temporalReservoir.Light_Weight = 0.0;
    temporalReservoir.Sum_Of_All_Weights = 0.0;
    temporalReservoir.Num_OF_Lights_In_Resevoir = 0.0;

    // Feed data from the last resevoir 
    UpdateReservoir(temporalReservoir, currentReservoir.Light_Index, p_hat_current * currentReservoir.Light_Weight * currentReservoir.Num_OF_Lights_In_Resevoir, currentReservoir.Num_OF_Lights_In_Resevoir, rngState);

    vec2 velocityUV = texelFetch(MotionVectorImage, TextCoord, 0).rg;
    vec2 screenPosPrevious = TextCoord - (velocityUV * pc.ScreenSize_Padding_FrameIndex_LightCount.xy);
    bool validHistory = all(greaterThanEqual(screenPosPrevious, vec2(0.0))) && all(lessThan(screenPosPrevious, pc.ScreenSize_Padding_FrameIndex_LightCount.xy));


    if (pc.TemporalReuse_SpatialReuse_ReSTIRwithDDGI_Padding_Flag.x > 0.5 && validHistory) {
        ivec2 prevCoord = ivec2(screenPosPrevious);      
        vec3 prevNormal = texelFetch(PrevNormalImage, prevCoord, 0).rgb;
        
        if (dot(prevNormal, surfaceData.normal) >= 0.9) {
            vec4 PrevResData = imageLoad(PrevResevoirImage, prevCoord);
            Reservoir historyReservoir;
            historyReservoir.Light_Index = uint(PrevResData.x);
            historyReservoir.Light_Weight = PrevResData.y;
            historyReservoir.Sum_Of_All_Weights = PrevResData.z;
            historyReservoir.Num_OF_Lights_In_Resevoir = min(PrevResData.w,20);

            vec3 historyRadiance = GetRadiance(historyReservoir.Light_Index, CameraPos, surfaceData, ViewDir, F, diffuse,IndirectRadiance);
            float p_hat_history = length(historyRadiance);
       
            UpdateReservoir(temporalReservoir, historyReservoir.Light_Index, p_hat_history * historyReservoir.Light_Weight * historyReservoir.Num_OF_Lights_In_Resevoir, historyReservoir.Num_OF_Lights_In_Resevoir, rngState);
        }
    }

    // Recalculate W for the temporal result
    vec3 tempRadiance = GetRadiance(temporalReservoir.Light_Index, CameraPos, surfaceData, ViewDir, F, diffuse,IndirectRadiance);
    float p_hat_temporal = length(tempRadiance);

    temporalReservoir.Light_Weight = (p_hat_temporal > 0.0) ? (1.0 / p_hat_temporal) * (temporalReservoir.Sum_Of_All_Weights / temporalReservoir.Num_OF_Lights_In_Resevoir) : 0.0;


    //SPATIAL REUSE
    Reservoir spatialReservoir;
    spatialReservoir.Light_Index = 0;
    spatialReservoir.Light_Weight = 0.0;
    spatialReservoir.Sum_Of_All_Weights = 0.0;
    spatialReservoir.Num_OF_Lights_In_Resevoir = 0.0;

    
    UpdateReservoir(spatialReservoir, temporalReservoir.Light_Index, p_hat_temporal * temporalReservoir.Light_Weight * temporalReservoir.Num_OF_Lights_In_Resevoir, temporalReservoir.Num_OF_Lights_In_Resevoir, rngState);

    if (pc.TemporalReuse_SpatialReuse_ReSTIRwithDDGI_Padding_Flag.y > 0.5) {
        int radius = 15; 
        for(int i = 0; i < 5; i++){

            vec2 offset = 2.0 * vec2(rand01(rngState), rand01(rngState)) - 1; // remaps it to (-1,1)
            ivec2 neighborCoord = clamp(ivec2(TextCoord + offset * float(radius)), ivec2(0), ivec2(pc.ScreenSize_Padding_FrameIndex_LightCount.xy - 1));

            vec3 neighborPos    = texelFetch(WorldPositionImage, neighborCoord, 0).xyz;
            vec3 neighborNormal = texelFetch(NormalImage, neighborCoord, 0).xyz;

            // Geometric consistency check
            if (dot(neighborNormal, surfaceData.normal) < 0.9) continue;//
            float planeDist = dot(neighborPos - surfaceData.worldPos, surfaceData.normal);
            if (abs(planeDist) > 0.05 * length(neighborPos - surfaceData.worldPos) + 0.01) continue;

            vec4 NeighbourResData = imageLoad(ResevoirImage, neighborCoord);
            Reservoir neighbourReservoir;
            neighbourReservoir.Light_Index = uint(NeighbourResData.x);
            neighbourReservoir.Light_Weight = NeighbourResData.y;
            neighbourReservoir.Num_OF_Lights_In_Resevoir = NeighbourResData.w;

            vec3 neighbourRadiance = GetRadiance(neighbourReservoir.Light_Index, CameraPos, surfaceData, ViewDir, F, diffuse, IndirectRadiance);
            float p_hat_neighbour = length(neighbourRadiance);

            float neighborM = min(neighbourReservoir.Num_OF_Lights_In_Resevoir, 20.0); 
            UpdateReservoir(spatialReservoir, neighbourReservoir.Light_Index, p_hat_neighbour * neighbourReservoir.Light_Weight * neighbourReservoir.Num_OF_Lights_In_Resevoir, neighbourReservoir.Num_OF_Lights_In_Resevoir, rngState);
        }
    }

     vec3 FinalRadiance = vec3(0.0);
    
    if (spatialReservoir.Sum_Of_All_Weights > 0.0) {
        
        if (spatialReservoir.Light_Index == GIIndex) {

            float p_hat_final = length(IndirectRadiance);

            if (p_hat_final > 0.0) {
                spatialReservoir.Light_Weight = (1.0 / p_hat_final) * (spatialReservoir.Sum_Of_All_Weights / spatialReservoir.Num_OF_Lights_In_Resevoir);
                
                FinalRadiance = IndirectRadiance * spatialReservoir.Light_Weight;
            } else {
                spatialReservoir.Light_Weight = 0.0;
                FinalRadiance = vec3(0.0);
            }

        } 
        else {

            LightData light = lights[spatialReservoir.Light_Index];
            vec3 RayDirection;
            float tMax;
            
            if (light.positionAndLightType.w > 0.5) {
                vec3 toLight = light.positionAndLightType.xyz - surfaceData.worldPos;
                RayDirection = normalize(toLight);
                tMax = length(toLight); 
            } else {
                RayDirection = normalize(-light.positionAndLightType.xyz); 
                tMax = 10000.0; 
            }
            
            bool Hit = TraceShadow(rayOrigin, RayDirection, tMax);
            
            vec3 radiance = GetRadiance(spatialReservoir.Light_Index, CameraPos, surfaceData, ViewDir, F, diffuse, IndirectRadiance);
            float p_hat_final = length(radiance);

            if (Hit && p_hat_final > 0.0) {
                spatialReservoir.Light_Weight = (1.0 / p_hat_final) * (spatialReservoir.Sum_Of_All_Weights / spatialReservoir.Num_OF_Lights_In_Resevoir);
                FinalRadiance = radiance * spatialReservoir.Light_Weight;
            } else {
                spatialReservoir.Light_Weight = 0.0;
                FinalRadiance = vec3(0.0);
            }
        }
    }

    if (spatialReservoir.Num_OF_Lights_In_Resevoir > 10.0) {
        float scale = 10.0 / spatialReservoir.Num_OF_Lights_In_Resevoir;
        spatialReservoir.Sum_Of_All_Weights *= scale;
        spatialReservoir.Num_OF_Lights_In_Resevoir = 10.0;
    }

    vec4 Res = vec4(spatialReservoir.Light_Index, spatialReservoir.Light_Weight, spatialReservoir.Sum_Of_All_Weights, spatialReservoir.Num_OF_Lights_In_Resevoir);
    imageStore(ResevoirImage, TextCoord, Res);            
    imageStore(ReSTIR_DIImage, TextCoord, vec4(FinalRadiance, 1));            
}