#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_ray_query : require
#extension GL_GOOGLE_include_directive : require
#include "DDGI_Include.glsl"
#include "PBR_Include.glsl"

struct LightData{
    vec4  positionAndLightType;
    vec4  colorAndAmbientStrength;
    vec4  CameraPositionAndLightIntensity;
};

layout(binding = 0) uniform LightUniformBuffer {
      LightData lights[100];
};

layout(binding = 1, rgba32f)  uniform image2D ResevoirImage;
layout(binding = 2)  uniform sampler2D WorldPositionImage;
layout(binding = 3)  uniform sampler2D NormalImage;
layout(binding = 4)  uniform sampler2D AlbedoImage;
layout(binding = 5)  uniform sampler2D MaterialImage;
layout (binding = 6) uniform sampler2D BlueNoise[63];
layout(set = 0, binding = 7) uniform accelerationStructureEXT topLevelAS;
layout (binding = 16, rgba32f) uniform image2D PrevResevoirImage;
layout (binding = 17) uniform sampler2D MotionVectorImage;
layout (binding = 18, rgba32f) uniform image2D ReSTIR_DIImage;
layout (binding = 19) uniform sampler2D PrevNormalImage;
layout(set = 1, binding = 0) uniform sampler2D  IrradianceStorageImage;
layout(set = 1, binding = 1) uniform sampler2D  VisibilityStorageImage;
layout (binding = 20) uniform sampler2D EmmisiveImage;

layout (binding = 21, rgba32f) uniform image2D GI_SamplePosImage;
layout (binding = 22, rgba32f) uniform image2D GI_SampleFluxImage;
layout (binding = 23, rgba32f) uniform image2D PrevGI_SamplePosImage;
layout (binding = 24, rgba32f) uniform image2D PrevGI_SampleFluxImage;

layout(push_constant) uniform PushConstant{
    vec4 CameraPosition;
    vec4 ScreenSize_Padding_FrameIndex_LightCount;
    vec4 GridBaseLocation_ScreenSizeWidth;
    vec4 ProbeSpacing_ScreenSizeHeight;
    vec4 ProbeCount;
    int   AtlasWidthSize;  
    int   ProbeSideLength; 
    int   GutterSize;      
    int   NumRays;
    vec4 Temporal_Spatial_Reuse_EnableDDGI_DDGI_Vertex_Flags;
    mat4  ProjectionViewMatrix;
} pc;

#include "ReSTIR_Include.glsl"

struct UnifiedPayload {
    vec4 data;  
    vec4 Emissive;  
    vec4 Position;
    vec4 Normal;
    vec4 Albedo;
};

layout(location = 0) rayPayloadEXT UnifiedPayload payload;

bool TraceShadow(vec3 origin, vec3 direction, float MaxDistance) {
    payload.data.x = 1.0;

    const uint rayFlags = gl_RayFlagsOpaqueEXT | 
                           gl_RayFlagsTerminateOnFirstHitEXT | 
                          gl_RayFlagsCullBackFacingTrianglesEXT;

    traceRayEXT(
        topLevelAS,
        rayFlags,
        0xFF,
        0, 0, 0,
        origin,
        0.3,
        direction,
        MaxDistance,
        0
    );

    return payload.data.x < 0.5;
}


void main() {
 bool bTemporalReuse = (pc.Temporal_Spatial_Reuse_EnableDDGI_DDGI_Vertex_Flags).x > 0.5;
 bool bSpatialReuse  = (pc.Temporal_Spatial_Reuse_EnableDDGI_DDGI_Vertex_Flags).y > 0.5;
 bool bDDGI          = (pc.Temporal_Spatial_Reuse_EnableDDGI_DDGI_Vertex_Flags).z > 0.5;
 int  DDGISamplingVertex = int(pc.Temporal_Spatial_Reuse_EnableDDGI_DDGI_Vertex_Flags.w);


 ivec2 TextCoord = ivec2(gl_LaunchIDEXT.xy);
  uint frameIndex = uint(pc.ScreenSize_Padding_FrameIndex_LightCount.z);
  int noiseIndex = int(frameIndex % 63);
  
  ivec2 noiseSize = textureSize(BlueNoise[noiseIndex], 0);
  vec2 noiseUV = vec2(TextCoord % noiseSize) / vec2(noiseSize);
  vec4 blueSample = texture(BlueNoise[noiseIndex], noiseUV);
  
  uint pixel_index = gl_LaunchIDEXT.x + gl_LaunchIDEXT.y * uint(pc.ScreenSize_Padding_FrameIndex_LightCount.y);
  uint seed = pcg_hash(pixel_index ^ pcg_hash(frameIndex));


 SurfaceData surfaceData;
 surfaceData.worldPos = texelFetch(WorldPositionImage, TextCoord, 0).xyz;

 if (surfaceData.worldPos == vec3(0.0)) {
     imageStore(ResevoirImage,      TextCoord, vec4(0.0));
     imageStore(ReSTIR_DIImage,     TextCoord, vec4(0.0));
     imageStore(GI_SamplePosImage,  TextCoord, vec4(0.0));
     imageStore(GI_SampleFluxImage, TextCoord, vec4(0.0));
     return; 
 }

 surfaceData.normal    = texelFetch(NormalImage, TextCoord, 0).xyz;
 surfaceData.albedo    = texelFetch(AlbedoImage, TextCoord, 0).xyz;
 vec2 material         = texelFetch(MaterialImage, TextCoord, 0).xy;
 surfaceData.metallic  = material.x;
 surfaceData.roughness = material.y; 

 vec3 CameraPos = pc.CameraPosition.xyz;
 vec3 ViewDir   = normalize(CameraPos - surfaceData.worldPos);
 vec3 F0        = mix(vec3(0.04), surfaceData.albedo, surfaceData.metallic);
 vec3 F         = fresnelSchlick(max(dot(surfaceData.normal, ViewDir), 0.0), F0);
 vec3 diffuse   = (vec3(1.0) - F) * (1.0 - surfaceData.metallic) * (surfaceData.albedo / 3.14159265359);
 vec3 rayOrigin = offsetPositionAlongNormal(surfaceData.worldPos, surfaceData.normal);

 vec3 DiffuseDirection = GetHemisphereSample(vec2(blueSample.x,blueSample.y), surfaceData.normal);

 vec2 velocityUV = texelFetch(MotionVectorImage, TextCoord, 0).rg;
 vec2 screenPosPrevious = TextCoord - (velocityUV * pc.ScreenSize_Padding_FrameIndex_LightCount.xy);
 ivec2 prevCoord = ivec2(TextCoord - velocityUV);
 // make sure we do not go offscreen
 bool validHistory = all(greaterThanEqual(screenPosPrevious, vec2(0.0))) && all(lessThan(screenPosPrevious, pc.ScreenSize_Padding_FrameIndex_LightCount.xy));

 uint initial_sample_count = 35;

   
   vec4 centerResData = imageLoad(ResevoirImage, TextCoord);

   Reservoir StoreageReservoir;
   StoreageReservoir.Light_Index = uint(centerResData.x);
   StoreageReservoir.Light_Weight = centerResData.y;
   StoreageReservoir.Sum_Of_All_Weights = centerResData.z;
   StoreageReservoir.Num_OF_Lights_In_Resevoir = centerResData.w;
   StoreageReservoir.Sample_Pos  = imageLoad(GI_SamplePosImage, TextCoord).xyz;
   StoreageReservoir.Sample_Flux = imageLoad(GI_SampleFluxImage, TextCoord).xyz;
   float p_hat_Storage  = imageLoad(GI_SampleFluxImage, TextCoord).w;

    ////TO DO IMPLMENT MULTIPLE IMPORTANCE SMAPLING( UNBIASED)

    //Spatial Reuse
    Reservoir spatialReservoir;
    spatialReservoir.Light_Index = 0;
    spatialReservoir.Light_Weight = 0.0;
    spatialReservoir.Sum_Of_All_Weights = 0.0;
    spatialReservoir.Num_OF_Lights_In_Resevoir = 0.0;

    spatialReservoir.Sample_Pos = StoreageReservoir.Sample_Pos;
    spatialReservoir.Sample_Flux = StoreageReservoir.Sample_Flux;
 
    if(UpdateReservoir(spatialReservoir, StoreageReservoir.Light_Index, p_hat_Storage * StoreageReservoir.Light_Weight * StoreageReservoir.Num_OF_Lights_In_Resevoir, StoreageReservoir.Num_OF_Lights_In_Resevoir, seed)) {
         spatialReservoir.Sample_Pos = StoreageReservoir.Sample_Pos;
         spatialReservoir.Sample_Flux = StoreageReservoir.Sample_Flux;
    }
   
    if (bSpatialReuse) {
        int radius = 15; 

        for(int i = 0; i < 10; i++){
            vec2 offset = 2.0 * vec2(rand(seed), rand(seed)) - 1.0;
            ivec2 neighborCoord = clamp(ivec2(TextCoord + offset * float(radius)), ivec2(0), ivec2(pc.ScreenSize_Padding_FrameIndex_LightCount.xy - 1));
   
            vec3 neighborPos    = texelFetch(WorldPositionImage, neighborCoord, 0).xyz;
            vec3 neighborNormal = texelFetch(NormalImage, neighborCoord, 0).xyz;
   
            if (dot(neighborNormal, surfaceData.normal) < 0.9) continue;
            float planeDist = dot(neighborPos - surfaceData.worldPos, surfaceData.normal);
            if (abs(planeDist) > 0.05 * length(neighborPos - surfaceData.worldPos) + 0.01) continue;
   
            
            if (neighborCoord.x < 0 || neighborCoord.x >= int(pc.ScreenSize_Padding_FrameIndex_LightCount.x) ||
                neighborCoord.y < 0 || neighborCoord.y >= int(pc.ScreenSize_Padding_FrameIndex_LightCount.y)) {
                continue;
            }
            
            vec4 NeighbourResData = imageLoad(ResevoirImage, neighborCoord);


            Reservoir neighbourReservoir;
            neighbourReservoir.Light_Index = uint(NeighbourResData.x);
            neighbourReservoir.Light_Weight = NeighbourResData.y;
            neighbourReservoir.Num_OF_Lights_In_Resevoir = NeighbourResData.w;

            if(neighbourReservoir.Light_Index == GIIndex) {
                neighbourReservoir.Sample_Pos  = imageLoad(GI_SamplePosImage , neighborCoord).xyz;
                neighbourReservoir.Sample_Flux = imageLoad(GI_SampleFluxImage, neighborCoord).xyz;
            } else {
                 neighbourReservoir.Sample_Pos = vec3(0.0);
                 neighbourReservoir.Sample_Flux = vec3(0.0);
            }
   
            // Re-evaluate neighbor sample at current pixel
            vec3 neighbourRadiance = EvaluateCandidateRadiance(neighbourReservoir.Light_Index, neighbourReservoir.Sample_Pos, neighbourReservoir.Sample_Flux, CameraPos, surfaceData, ViewDir, F, diffuse);
            float p_hat_neighbour = length(neighbourRadiance);
   
            if(UpdateReservoir(spatialReservoir, neighbourReservoir.Light_Index, p_hat_neighbour * neighbourReservoir.Light_Weight * neighbourReservoir.Num_OF_Lights_In_Resevoir, neighbourReservoir.Num_OF_Lights_In_Resevoir, seed)) {
                spatialReservoir.Sample_Pos = neighbourReservoir.Sample_Pos;
                spatialReservoir.Sample_Flux = neighbourReservoir.Sample_Flux;
            }
        }
    }

    //Final Shading
   vec3 FinalRadiance = vec3(0.0);
   
    if (spatialReservoir.Sum_Of_All_Weights > 0.0) {

        vec3 radiance = EvaluateCandidateRadiance(spatialReservoir.Light_Index, spatialReservoir.Sample_Pos, spatialReservoir.Sample_Flux, CameraPos, surfaceData, ViewDir, F, diffuse);
        
        float p_hat_final = length(radiance);
        bool isVisible = true;
   
          ////////////////////////////////////////////
        if (spatialReservoir.Light_Index != GIIndex && p_hat_final > 0.0) {
            LightData light = lights[spatialReservoir.Light_Index];
            vec3 shadowDir;
            float tMax;
   
            if (light.positionAndLightType.w > 0.5) { 
                tMax = length(light.positionAndLightType.xyz - surfaceData.worldPos);
                shadowDir = SoftShadow(light.positionAndLightType.xyz, surfaceData.worldPos, 0.25, blueSample.x, blueSample.x);
            } else { 
                tMax = 10000.0;
                shadowDir = DirectionalSoftShadow(normalize(-light.positionAndLightType.xyz), 0.009, blueSample.x, blueSample.x);
            }
   
            isVisible = TraceShadow(rayOrigin, shadowDir, tMax);
        }
   
       ////////////////////////////////////////////
       if (spatialReservoir.Light_Index == GIIndex) {
           vec3 lightVec = normalize(spatialReservoir.Sample_Pos - surfaceData.worldPos);
           float tMax = length(spatialReservoir.Sample_Pos - surfaceData.worldPos);
           isVisible = TraceShadow(rayOrigin, lightVec, tMax); 

           radiance *= surfaceData.albedo;
       }
   
       ////////////////////////////////////////////
        if (isVisible && p_hat_final > 0.0) {
            float avgWeight = spatialReservoir.Sum_Of_All_Weights / spatialReservoir.Num_OF_Lights_In_Resevoir;
            spatialReservoir.Light_Weight = (1.0 / p_hat_final) * avgWeight;
            FinalRadiance = radiance * spatialReservoir.Light_Weight;
        } else {
            spatialReservoir.Light_Weight = 0.0;
        }

    }
   

    if (spatialReservoir.Num_OF_Lights_In_Resevoir > MaxResevoirVolume) {
        float scale = MaxResevoirVolume / spatialReservoir.Num_OF_Lights_In_Resevoir;
        spatialReservoir.Sum_Of_All_Weights *= scale;
        spatialReservoir.Num_OF_Lights_In_Resevoir = MaxResevoirVolume;
    }
     
   
    vec4 Res = vec4(spatialReservoir.Light_Index, spatialReservoir.Light_Weight, spatialReservoir.Sum_Of_All_Weights, spatialReservoir.Num_OF_Lights_In_Resevoir);
    
    imageStore(PrevResevoirImage     , TextCoord, Res);
    imageStore(PrevGI_SamplePosImage , TextCoord, vec4(spatialReservoir.Sample_Pos, 1.0));
    imageStore(PrevGI_SampleFluxImage, TextCoord, vec4(spatialReservoir.Sample_Flux, 1.0));
   
     vec3 Emissive  = texelFetch(EmmisiveImage, TextCoord, 0).xyz;

if (DDGISamplingVertex == 0 && bDDGI) {
            vec3 VeiwDirection = normalize(pc.CameraPosition.xyz - surfaceData.worldPos);
               vec3 SamplePosition = surfaceData.worldPos + (VeiwDirection * 2.2);


         vec3 irr = GetGIRadiance(SamplePosition, surfaceData.normal);
         vec3 OutGoing = FinalRadiance + irr * surfaceData.albedo / 3.14159265;
         
         imageStore(ReSTIR_DIImage, TextCoord, vec4(OutGoing + Emissive, 1.0));              
      return;
    }
   
    imageStore(ReSTIR_DIImage, TextCoord, vec4(FinalRadiance + Emissive, 1.0));              
 }