#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_ray_query : require
#extension GL_GOOGLE_include_directive : require
#include "DDGI_Include.glsl"
#include "PBR_Include.glsl"

struct LightData{
    vec4  positionAndLightType;
    vec4  colorAndAmbientStrength;
    vec4  CameraPositionAndLightIntensity;
};

layout(binding = 0) uniform LightUniformBuffer {
      LightData lights[100];
};

layout(binding = 1, rgba16f)  uniform image2D ResevoirImage;
layout(binding = 2)  uniform sampler2D WorldPositionImage;
layout(binding = 3)  uniform sampler2D NormalImage;
layout(binding = 4)  uniform sampler2D AlbedoImage;
layout(binding = 5)  uniform sampler2D MaterialImage;
layout (binding = 6) uniform sampler2D BlueNoise[63];
layout(set = 0, binding = 7) uniform accelerationStructureEXT topLevelAS;
layout (binding = 16, rgba16f) uniform image2D PrevResevoirImage;
layout (binding = 17) uniform sampler2D MotionVectorImage;
layout (binding = 18, rgba16f) uniform image2D ReSTIR_DIImage;
layout (binding = 19) uniform sampler2D PrevNormalImage;
layout(set = 1, binding = 0) uniform sampler2D  IrradianceStorageImage;
layout(set = 1, binding = 1) uniform sampler2D  VisibilityStorageImage;
layout (binding = 20) uniform sampler2D EmmisiveImage;

layout(push_constant) uniform PushConstant{
    vec4 CameraPosition;
    vec4 ScreenSize_Padding_FrameIndex_LightCount;
    vec4 GridBaseLocation_ScreenSizeWidth;
    vec4 ProbeSpacing_ScreenSizeHeight;
    vec4 ProbeCount;
    int   AtlasWidthSize;  
    int   ProbeSideLength; 
    int   GutterSize;      
    int   NumRays;
    vec4 Temporal_Spatial_Reuse_EnableDDGI_DDGI_Vertex_Flags;
    mat4  ProjectionViewMatrix;
} pc;

const int GIIndex = 900;

 const float MaxResevoirVolume = 10.0; 

uint pcg_hash(uint seed) {
    uint state = seed * 747796405u + 2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

float rand01(inout uint seed) {
    seed = pcg_hash(seed);
    return float(seed) * (1.0 / 4294967296.0); 
}

uint initRNG(vec2 pixel, vec2 screenSize, uint frameNumber) {
    uint pixelIndex = uint(pixel.x) + uint(pixel.y) * uint(screenSize.x);
    uint s = pcg_hash(pixelIndex);
    return pcg_hash(s ^ pcg_hash(frameNumber)); 
}

struct SurfaceData {
    vec3  worldPos;
    vec3  normal;
    vec3  albedo;
    float metallic;
    float roughness;
};

struct UnifiedPayload {
    vec4 data;  
    vec4 Emissive;  
    vec4 Position;
    vec4 Normal;
    vec4 Albedo;
};

layout(location = 0) rayPayloadEXT UnifiedPayload payload;

bool TraceShadow(vec3 origin, vec3 direction, float MaxDistance) {
    payload.data.x = 1.0;

    const uint rayFlags = gl_RayFlagsOpaqueEXT | 
                           gl_RayFlagsTerminateOnFirstHitEXT | 
                          gl_RayFlagsCullBackFacingTrianglesEXT;

    traceRayEXT(
        topLevelAS,
        rayFlags,
        0xFF,
        0, 0, 0,
        origin,
        0.1,
        direction,
        MaxDistance,
        0
    );

    return payload.data.x < 0.5;
}

vec3 offsetPositionAlongNormal(vec3 ViewPosition, vec3 normal) {
    return ViewPosition + 0.06 * normal;
}

struct Reservoir {
    uint  Light_Index; 
    float Light_Weight; 
    float Sum_Of_All_Weights; 
    float Num_OF_Lights_In_Resevoir;

    //Virtual Light Data
    vec3  Sample_Pos;  
    vec3  Sample_Flux;   
};

bool UpdateReservoir(inout Reservoir reservoir, uint LightIndex, float Weight, float c, inout uint seed) {
    reservoir.Sum_Of_All_Weights += Weight;
    reservoir.Num_OF_Lights_In_Resevoir += c;

    if (rand01(seed) < (Weight / reservoir.Sum_Of_All_Weights)) {
        reservoir.Light_Index = LightIndex;
        return true;
    }
    return false;
}

vec3 GetPerpendicularVector(vec3 v) {
    return normalize(cross(v, abs(v.x) > abs(v.z) ? vec3(0.0, 0.0, 1.0) : vec3(1.0, 0.0, 0.0)));
}

vec3 EvaluateBSDF(SurfaceData surface, vec3 ViewDir, vec3 LightDir) {
    // 1. Diffuse (Lambertian)
    vec3 F0 = mix(vec3(0.04), surface.albedo, surface.metallic);
    vec3 F = fresnelSchlick(max(dot(surface.normal, ViewDir), 0.0), F0);
    vec3 kD = (vec3(1.0) - F) * (1.0 - surface.metallic);
    vec3 diffuse = kD * (surface.albedo / 3.14159265359);

    // 2. Specular (GGX)
    vec3 halfwayDir = normalize(LightDir + ViewDir);
    float NDF = DistributionGGX(surface.normal, halfwayDir, surface.roughness);      
    float G_spec = GeometrySmith(surface.normal, ViewDir, LightDir, surface.roughness);
    
    vec3 numerator = NDF * G_spec * F;
    float denominator = 4.0 * max(dot(surface.normal, ViewDir), 0.0) 
                            * max(dot(surface.normal, LightDir), 0.0) + 0.0001;
    vec3 specular = numerator / denominator;

    return diffuse + specular;
}
vec3 GetHemisphereSample(vec2 randVal, vec3 HitNormal) {
    vec3 bitangent = GetPerpendicularVector(HitNormal);
    vec3 tangent = cross(bitangent, HitNormal);
    float r = sqrt(randVal.x);
    float phi = 2.0 * 3.14159265 * randVal.y;
    
    return tangent * (r * cos(phi)) + bitangent * (r * sin(phi)) + HitNormal.xyz * sqrt(max(0.0, 1.0 - randVal.x));
}

vec3 GetGIRadiance(vec3 worldPos, vec3 normal, vec3 albedo) {

    vec3 ViewVec = normalize(pc.CameraPosition.xyz - worldPos);
    float biasAmount = pc.ProbeSpacing_ScreenSizeHeight.x * 0.2; 
    vec3 BiasedPos = worldPos + (normal * biasAmount); 

    vec3 Irradiance = SampleIrradiance(
        IrradianceStorageImage, VisibilityStorageImage,
        BiasedPos,          
        normal,             
        pc.GridBaseLocation_ScreenSizeWidth.xyz, 
        pc.ProbeSpacing_ScreenSizeHeight.xyz,
        ivec3(pc.ProbeCount.xyz), 
        pc.ProbeSideLength, pc.GutterSize, pc.AtlasWidthSize,
        pc.ProbeSideLength, pc.GutterSize, pc.AtlasWidthSize, 
        pc.CameraPosition.xyz
    );

    return Irradiance * (albedo / 3.14159265359);
}

vec3 GetLightRadiance(LightData light, vec3 cameraPos, SurfaceData surface, vec3 ViewDir, vec3 F, vec3 diffuse);

vec3 GetRadiance(uint lightIndex, vec3 cameraPos, SurfaceData surface, vec3 ViewDir, vec3 F, vec3 diffuse) {
    if (lightIndex == GIIndex) {
        return GetGIRadiance(surface.worldPos, surface.normal, surface.albedo);
    }
    return GetLightRadiance(lights[lightIndex], cameraPos, surface, ViewDir, F, diffuse);
}

vec3 GetLightRadiance(LightData light, vec3 cameraPos, SurfaceData surface, vec3 ViewDir, vec3 F, vec3 diffuse) {
    vec3 radiance   = vec3(0.0);
    vec3 LightDir   = vec3(0.0);

    if (light.positionAndLightType.w > 0.5) {
        vec3 LightPos = light.positionAndLightType.xyz;
        LightDir = normalize(LightPos - surface.worldPos);
        float Distance = length(LightPos - surface.worldPos);
        float Attenuation = 1.0 / (1.0 + 0.09 * Distance + 0.032 * (Distance * Distance));
        radiance = light.colorAndAmbientStrength.rgb * Attenuation;
    } else {
        LightDir = normalize(-light.positionAndLightType.xyz);
        radiance = light.colorAndAmbientStrength.rgb;
    }

    vec3 halfwayDir = normalize(LightDir + ViewDir);
    float NDF = DistributionGGX(surface.normal, halfwayDir, surface.roughness);      
    float G = GeometrySmith(surface.normal, ViewDir, LightDir, surface.roughness);
    vec3 numerator = NDF * G * F;
    float denominator = 4.0 * max(dot(surface.normal, ViewDir), 0.0) * max(dot(surface.normal, LightDir), 0.0) + 0.0001;
    vec3 specular = (numerator / denominator);

    float NdotL = max(dot(surface.normal, LightDir), 0.0);
    return (diffuse + specular) * radiance * NdotL * light.CameraPositionAndLightIntensity.a;
}

// Gold Noise
float PHI = 1.61803398874989484820459;    
float gold_noise(vec2 xy, float seed){
    return fract(tan(distance(xy*PHI, xy)*seed)*xy.x);
}

void main() {
    bool bTemporalReuse = (pc.Temporal_Spatial_Reuse_EnableDDGI_DDGI_Vertex_Flags).x > 0.5;
    bool bSpatialReuse  = (pc.Temporal_Spatial_Reuse_EnableDDGI_DDGI_Vertex_Flags).y > 0.5;
    bool bDDGI          = (pc.Temporal_Spatial_Reuse_EnableDDGI_DDGI_Vertex_Flags).z > 0.5;
    int  DDGISamplingVertex = int(pc.Temporal_Spatial_Reuse_EnableDDGI_DDGI_Vertex_Flags.w);
   

    ivec2 TextCoord = ivec2(gl_LaunchIDEXT.xy + 0.5);
    uint rngState = initRNG(gl_LaunchIDEXT.xy, gl_LaunchSizeEXT.xy, uint(pc.ScreenSize_Padding_FrameIndex_LightCount.z));
    float r1 = rand01(rngState);
    float r2 = rand01(rngState);

    SurfaceData surfaceData;
    surfaceData.worldPos = texelFetch(WorldPositionImage, TextCoord, 0).xyz;

    if (surfaceData.worldPos == vec3(0.0)) {
        imageStore(ResevoirImage, TextCoord, vec4(0.0));
        imageStore(ReSTIR_DIImage, TextCoord, vec4(0.0));
        return; 
    }

    surfaceData.normal    = texelFetch(NormalImage, TextCoord, 0).xyz;
    surfaceData.albedo    = texelFetch(AlbedoImage, TextCoord, 0).xyz;
    vec2 material         = texelFetch(MaterialImage, TextCoord, 0).xy;
    surfaceData.metallic  = material.x;
    surfaceData.roughness = material.y; 
   
    vec3 CameraPos = pc.CameraPosition.xyz;
    vec3 ViewDir   = normalize(CameraPos - surfaceData.worldPos);
    vec3 F0        = mix(vec3(0.04), surfaceData.albedo, surfaceData.metallic);
    vec3 F         = fresnelSchlick(max(dot(surfaceData.normal, ViewDir), 0.0), F0);
    vec3 diffuse   = (vec3(1.0) - F) * (1.0 - surfaceData.metallic) * (surfaceData.albedo / 3.14159265359);
    vec3 rayOrigin = offsetPositionAlongNormal(surfaceData.worldPos, surfaceData.normal);

    vec2 uv = (vec2(TextCoord) + 0.5) / vec2(128,128);
    int DiffuseRandIndex = int(pc.ScreenSize_Padding_FrameIndex_LightCount.z - 3) % 63;
    vec3 DiffuseDirection = GetHemisphereSample(textureLod(BlueNoise[DiffuseRandIndex], uv, 0).rg, surfaceData.normal);

    vec2 velocityUV = texelFetch(MotionVectorImage, TextCoord, 0).rg;
    vec2 screenPosPrevious = TextCoord - (velocityUV * pc.ScreenSize_Padding_FrameIndex_LightCount.xy);
    ivec2 prevCoord = ivec2(screenPosPrevious);      
    bool validHistory = all(greaterThanEqual(screenPosPrevious, vec2(0.0))) && all(lessThan(screenPosPrevious, pc.ScreenSize_Padding_FrameIndex_LightCount.xy));

    if (validHistory) {
      vec3 prevNormal = texelFetch(PrevNormalImage, prevCoord, 0).rgb;
      validHistory = dot(prevNormal, surfaceData.normal) >= 0.9;
    }

    uint initial_sample_count = validHistory ? 20 : 35;

    Reservoir currentReservoir;
    currentReservoir.Light_Index = 0;
    currentReservoir.Light_Weight = 0.0;
    currentReservoir.Sum_Of_All_Weights = 0.0;
    currentReservoir.Num_OF_Lights_In_Resevoir = 0.0;
    currentReservoir.Sample_Pos = vec3(0.0); 
    currentReservoir.Sample_Flux = vec3(0.0);

    int TotalNumOfLights = int(pc.ScreenSize_Padding_FrameIndex_LightCount.w);
    float pdf = 1.0 / float(TotalNumOfLights); 
    float p_hat_current = 0.0; 

    //Initial Candidates Lights
    for (uint i = 0; i < initial_sample_count; i++) {  
        uint lightIndex = min(uint(rand01(rngState) * float(TotalNumOfLights)), uint(TotalNumOfLights - 1)); 
        vec3 RadianceCandidate = GetLightRadiance(lights[lightIndex], CameraPos, surfaceData, ViewDir, F, diffuse);  
        float p_hat = length(RadianceCandidate);
        float WeightOfLight = p_hat / pdf; 

        if(UpdateReservoir(currentReservoir, lightIndex, WeightOfLight, 1.0, rngState)){
            p_hat_current = p_hat;
        }
    }

    //Initial Candidate GI 
 if (DDGISamplingVertex > 0 && bDDGI) {
        
        payload.data     = vec4(0);
        payload.Emissive = vec4(0);
        payload.Position = vec4(0);
        payload.Normal   = vec4(0);
        payload.Albedo   = vec4(0);
        

        traceRayEXT(topLevelAS, 
            gl_RayFlagsOpaqueEXT | gl_RayFlagsTerminateOnFirstHitEXT | gl_RayFlagsCullBackFacingTrianglesEXT, 
            0xFF, 0, 0, 0, 
            rayOrigin, 0.01, DiffuseDirection, 1000.0, 0);

        
        vec3 y_pos = payload.Position.xyz;
        vec3 y_norm = normalize(payload.Normal.xyz);
        vec3 y_albedo = payload.Albedo.xyz;
        vec3 y_emissive = payload.Emissive.xyz;
       
        vec3 y_radiance = y_emissive + GetGIRadiance(y_pos, y_norm, y_albedo);

        float GI_p_hat = length(y_radiance); 
        float WeightOfLight = GI_p_hat / pdf; 
        
        if (GI_p_hat > 0.0) {

            if(UpdateReservoir(currentReservoir, GIIndex, WeightOfLight, 1.0, rngState)){

                p_hat_current = GI_p_hat;
                
                currentReservoir.Sample_Pos = y_pos;
                currentReservoir.Sample_Flux = y_radiance;
            }
        }
    }

    if (p_hat_current > 0.0) {    
        currentReservoir.Light_Weight = (1.0 / p_hat_current) * (currentReservoir.Sum_Of_All_Weights / currentReservoir.Num_OF_Lights_In_Resevoir);
    } 
    else {
        currentReservoir.Light_Weight = 0.0;
    }

    Reservoir spatialReservoir = currentReservoir;

   // //Temporal Reuse
   // Reservoir temporalReservoir;
   // temporalReservoir.Light_Index = 0;
   // temporalReservoir.Light_Weight = 0.0;
   // temporalReservoir.Sum_Of_All_Weights = 0.0;
   // temporalReservoir.Num_OF_Lights_In_Resevoir = 0.0;
   //
   // UpdateReservoir(temporalReservoir, currentReservoir.Light_Index, p_hat_current * currentReservoir.Light_Weight * currentReservoir.Num_OF_Lights_In_Resevoir, currentReservoir.Num_OF_Lights_In_Resevoir, rngState);
   //
   // if (bTemporalReuse && validHistory) {
   //     vec3 prevNormal = texelFetch(PrevNormalImage, prevCoord, 0).rgb;
   //     if (dot(prevNormal, surfaceData.normal) >= 0.9) {
   //         vec4 PrevResData = imageLoad(PrevResevoirImage, prevCoord);
   //         Reservoir historyReservoir;
   //         historyReservoir.Light_Index = uint(PrevResData.x);
   //         historyReservoir.Light_Weight = PrevResData.y;
   //         historyReservoir.Sum_Of_All_Weights = PrevResData.z;
   //         historyReservoir.Num_OF_Lights_In_Resevoir = min(PrevResData.w, MaxResevoirVolume);
   //
   //         // Re-evaluate history sample at current pixel
   //         vec3 historyRadiance = GetRadiance(historyReservoir.Light_Index, CameraPos, surfaceData, ViewDir, F, diffuse);
   //         float p_hat_history = length(historyRadiance);
   //     
   //         UpdateReservoir(temporalReservoir, historyReservoir.Light_Index, p_hat_history * historyReservoir.Light_Weight * historyReservoir.Num_OF_Lights_In_Resevoir, historyReservoir.Num_OF_Lights_In_Resevoir, rngState);
   //     }
   // }
   //
   // vec3 tempRadiance = GetRadiance(temporalReservoir.Light_Index, CameraPos, surfaceData, ViewDir, F, diffuse);
   // float p_hat_temporal = length(tempRadiance);
   // temporalReservoir.Light_Weight = (p_hat_temporal > 0.0) ? (1.0 / p_hat_temporal) * (temporalReservoir.Sum_Of_All_Weights / temporalReservoir.Num_OF_Lights_In_Resevoir) : 0.0;
   //
   //
   // //Spatial Reuse
   // Reservoir spatialReservoir;
   // spatialReservoir.Light_Index = 0;
   // spatialReservoir.Light_Weight = 0.0;
   // spatialReservoir.Sum_Of_All_Weights = 0.0;
   // spatialReservoir.Num_OF_Lights_In_Resevoir = 0.0;
   //
   // UpdateReservoir(spatialReservoir, temporalReservoir.Light_Index, p_hat_temporal * temporalReservoir.Light_Weight * temporalReservoir.Num_OF_Lights_In_Resevoir, temporalReservoir.Num_OF_Lights_In_Resevoir, rngState);
   //
   // if (bSpatialReuse) {
   //     int radius = 15; 
   //     for(int i = 0; i < 5; i++){
   //         vec2 offset = 2.0 * vec2(rand01(rngState), rand01(rngState)) - 1; 
   //         ivec2 neighborCoord = clamp(ivec2(TextCoord + offset * float(radius)), ivec2(0), ivec2(pc.ScreenSize_Padding_FrameIndex_LightCount.xy - 1));
   //
   //         vec3 neighborPos    = texelFetch(WorldPositionImage, neighborCoord, 0).xyz;
   //         vec3 neighborNormal = texelFetch(NormalImage, neighborCoord, 0).xyz;
   //
   //         if (dot(neighborNormal, surfaceData.normal) < 0.9) continue;
   //         float planeDist = dot(neighborPos - surfaceData.worldPos, surfaceData.normal);
   //         if (abs(planeDist) > 0.05 * length(neighborPos - surfaceData.worldPos) + 0.01) continue;
   //
   //         vec4 NeighbourResData = imageLoad(ResevoirImage, neighborCoord);
   //         Reservoir neighbourReservoir;
   //         neighbourReservoir.Light_Index = uint(NeighbourResData.x);
   //         neighbourReservoir.Light_Weight = NeighbourResData.y;
   //         neighbourReservoir.Num_OF_Lights_In_Resevoir = NeighbourResData.w;
   //
   //         // Re-evaluate neighbor sample at current pixel
   //         vec3 neighbourRadiance = GetRadiance(neighbourReservoir.Light_Index, CameraPos, surfaceData, ViewDir, F, diffuse);
   //         float p_hat_neighbour = length(neighbourRadiance);
   //
   //         UpdateReservoir(spatialReservoir, neighbourReservoir.Light_Index, p_hat_neighbour * neighbourReservoir.Light_Weight * neighbourReservoir.Num_OF_Lights_In_Resevoir, neighbourReservoir.Num_OF_Lights_In_Resevoir, rngState);
   //     }
   // }

    //Final Shading
    vec3 FinalRadiance = vec3(0.0);

    if (spatialReservoir.Sum_Of_All_Weights > 0.0) {
        vec3 radiance = GetRadiance(spatialReservoir.Light_Index, CameraPos, surfaceData, ViewDir, F, diffuse);
        float p_hat_final = length(radiance);
        bool isVisible = true;

        if (spatialReservoir.Light_Index != GIIndex && p_hat_final > 0.0) {
            LightData light = lights[spatialReservoir.Light_Index];
            vec3 shadowDir;
            float tMax;

            if (light.positionAndLightType.w > 0.5) { 
                tMax = length(light.positionAndLightType.xyz - surfaceData.worldPos);
                shadowDir = SoftShadow(light.positionAndLightType.xyz, surfaceData.worldPos, 0.25, r1, r2);
            } else { 
                tMax = 10000.0;
                shadowDir = DirectionalSoftShadow(normalize(-light.positionAndLightType.xyz), 0.009, r1, r2);
            }

            isVisible = TraceShadow(rayOrigin, shadowDir, tMax);
        }

        if (spatialReservoir.Light_Index == GIIndex) {

             vec3 lightVec = normalize(spatialReservoir.Sample_Pos - surfaceData.worldPos);
               float  tMax = length(spatialReservoir.Sample_Pos - surfaceData.worldPos);

                  isVisible = TraceShadow(rayOrigin, lightVec, tMax);
                  
              if (isVisible) {
              
                  vec3 bsdf = EvaluateBSDF(surfaceData, ViewDir, lightVec);
                  
                  radiance = spatialReservoir.Sample_Flux * bsdf; 
                  
                  p_hat_final = length(spatialReservoir.Sample_Flux); 
              }
            
       }


        if (isVisible && p_hat_final > 0.0) {
            float avgWeight = spatialReservoir.Sum_Of_All_Weights / spatialReservoir.Num_OF_Lights_In_Resevoir;
            spatialReservoir.Light_Weight = (1.0 / p_hat_final) * avgWeight;
            FinalRadiance = radiance * spatialReservoir.Light_Weight;
        } else {
            spatialReservoir.Light_Weight = 0.0;
        }
    }

    if (spatialReservoir.Num_OF_Lights_In_Resevoir > MaxResevoirVolume) {
        float scale = MaxResevoirVolume / spatialReservoir.Num_OF_Lights_In_Resevoir;
        spatialReservoir.Sum_Of_All_Weights *= scale;
        spatialReservoir.Num_OF_Lights_In_Resevoir = MaxResevoirVolume;
    }
     
   vec3 Emissive  = texelFetch(EmmisiveImage, TextCoord, 0).xyz;

    vec4 Res = vec4(spatialReservoir.Light_Index, spatialReservoir.Light_Weight, spatialReservoir.Sum_Of_All_Weights, spatialReservoir.Num_OF_Lights_In_Resevoir);
    imageStore(ResevoirImage, TextCoord, Res);             
    imageStore(ReSTIR_DIImage, TextCoord, vec4(FinalRadiance + Emissive, 1));             
}