#version 450

layout(push_constant) uniform ImageSize{
    vec4 GridBaseLocation_ScreenSizeWidth;
    vec4 ProbeSpacing_ScreenSizeHeight;
    vec4 ProbeCount;

    ///////////////////////

    int   AtlasWidthSize;  
    int   ProbeSideLength; 
    int   GutterSize;      
    int   NumRays;    
}pc;

layout(binding = 0)   uniform sampler2D  PositionImage;
layout(binding = 1)   uniform sampler2D  NormalImage;
layout(binding = 2, rgba16f)   uniform image2D  IrradianceStorageImage;
layout(binding = 3, rgba16f)   uniform image2D  SampledGIImage;
layout(binding = 4, rgba16f)   uniform image2D  VisibilityStorageImage;

layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

ivec3 WorldToGrid(vec3 WorldPosition,vec3 GridBaseLocation,vec3 GridSpacing,vec3 ProbeCount){

    vec3 GridIndex = (WorldPosition - GridBaseLocation) / GridSpacing; // Get the position in the grid

    vec3 ClampedGridIndex = clamp(GridIndex, vec3(0), vec3(ProbeCount - 1)); // Clamp to the grid size
    return ivec3(ClampedGridIndex);
}

float sign_not_zero(in float k) {
    return (k >= 0.0) ? 1.0 : -1.0;
}

vec2 sign_not_zero2(in vec2 v) {
    return vec2(sign_not_zero(v.x), sign_not_zero(v.y));
}

vec2 oct_encode(in vec3 v) {
    float l1norm = abs(v.x) + abs(v.y) + abs(v.z);
    vec2 result = v.xy * (1.0 / l1norm);
    if (v.z < 0.0) {
        result = (1.0 - abs(result.yx)) * sign_not_zero2(result.xy);
    }
    return result;
}

ivec2 GetProbeTexel( vec3 direction, ivec3 probeIndex)
{

    vec2 octahedral_coordinates = oct_encode(normalize(direction));
    // 2. Map it to [0, 1]
     octahedral_coordinates = (octahedral_coordinates * 0.5) + 0.5f;

    int probeSideWithGutter = pc.ProbeSideLength + pc.GutterSize;
    int probesPerRow        = pc.AtlasWidthSize / probeSideWithGutter;
    int linearIndex         = probeIndex.x + probeIndex.y * int(pc.ProbeCount.x) + probeIndex.z * int(pc.ProbeCount.x * pc.ProbeCount.y);

    int cellOffsetX = (linearIndex % probesPerRow) * probeSideWithGutter;
    int cellOffsetY = (linearIndex / probesPerRow) * probeSideWithGutter;


    vec2 internalPixelOffset = octahedral_coordinates * float(pc.ProbeSideLength);

    int   border_offset = pc.GutterSize / 2; 
    ivec2 TopLeft = ivec2(cellOffsetX, cellOffsetY) + ivec2(border_offset);

    ivec2 FinalTexel = TopLeft + ivec2(internalPixelOffset) ;

    return FinalTexel;
}


void main() 
{

    int   Width            = int(pc.GridBaseLocation_ScreenSizeWidth.w);
    int   Height           = int(pc.ProbeSpacing_ScreenSizeHeight.w);
    vec3  GridBaseLocation = pc.GridBaseLocation_ScreenSizeWidth.xyz;
    vec3  ProbeSpacing     = pc.ProbeSpacing_ScreenSizeHeight.xyz;
    ivec3 ProbeCount       = ivec3(pc.ProbeCount.xyz);

    ivec2 TextlCord        = ivec2(gl_GlobalInvocationID.xy);

    vec2 UV = (vec2(TextlCord) + 0.5) / vec2(Width,Height); // + 0.5 gives us the middle of the TEXEL not the edge

    vec3 Position = texture(PositionImage,UV).rgb;
    vec3 Normal   = texture(NormalImage,  UV).rgb;
    vec3 GridIndexF = (Position - GridBaseLocation) / ProbeSpacing;
    vec3 Alpha = fract(GridIndexF);


    ivec3 GridIndex = WorldToGrid(Position,GridBaseLocation,ProbeSpacing,vec3(ProbeCount));

     ivec3 Offsets[8] = {
         ivec3(0,0,0), ivec3(1,0,0),
         ivec3(0,1,0), ivec3(1,1,0),
         ivec3(0,0,1), ivec3(1,0,1),
         ivec3(0,1,1), ivec3(1,1,1)
     };


     vec4 Irradiance = vec4(0);

     for(int i = 0; i < 8; i++){

         ivec3 ProbeIndex        = clamp((GridIndex + Offsets[i]),ivec3(0),ProbeCount);
         vec3 ProbeWorldPosition = GridBaseLocation + (vec3(ProbeIndex) * ProbeSpacing);

         ivec2 irradiance_texel = GetProbeTexel(Normal,ProbeIndex);

         vec3 dir = Position  -  ProbeWorldPosition ;
         float r = length(dir);
         dir *= -1.0 / r;


         float weight = (dot(dir, Normal) + 1) * 0.5;
         weight = (weight * weight) + 0.2;

         float wx = (Offsets[i].x == 1) ? Alpha.x : (1.0 - Alpha.x);
         float wy = (Offsets[i].y == 1) ? Alpha.y : (1.0 - Alpha.y);
         float wz = (Offsets[i].z == 1) ? Alpha.z : (1.0 - Alpha.z);
         float trilinearWeight = wx * wy * wz;

         weight *= trilinearWeight + 0.001;

          //////////////////////////////////////////////////////////////
          ivec2 visibility_texel = GetProbeTexel(dir, ProbeIndex);
          vec2 DepthInfo =  imageLoad(VisibilityStorageImage, visibility_texel).rg;

          float Mean  = DepthInfo.x; 
          float Mean2 = DepthInfo.y; 
          
         float chebyshev_weight = 1.0;

         if(r >  Mean) {
         
          float variance = abs((Mean * Mean) - Mean2);
          const float distanceDiff = r - Mean;
          chebyshev_weight = variance / (variance + (distanceDiff * distanceDiff));
            
          chebyshev_weight = max((chebyshev_weight * chebyshev_weight * chebyshev_weight), 0.0f);

         }

         chebyshev_weight = max(0.05f, chebyshev_weight);
         weight *= chebyshev_weight;

         vec3 probeIrradiance = sqrt(imageLoad(IrradianceStorageImage, irradiance_texel).rgb) * weight;
         Irradiance += vec4(probeIrradiance, weight);
     }
     
       vec3 ComputedIrradiance = (Irradiance.rgb * (1.0 / Irradiance.a));

       ComputedIrradiance = ComputedIrradiance * ComputedIrradiance;

    imageStore(SampledGIImage, ivec2(gl_GlobalInvocationID.xy), vec4(ComputedIrradiance,1));

}
