#version 450
#extension GL_GOOGLE_include_directive : require
#include "DDGI_Include.glsl"

layout(push_constant) uniform ImageSize{
    vec4 GridBaseLocation_ScreenSizeWidth;
    vec4 ProbeSpacing_ScreenSizeHeight;
    vec4 ProbeCount;

    ///////////////////////

    int   AtlasWidthSize;  
    int   ProbeSideLength; 
    int   GutterSize;      
    int   NumRays;
    vec4  CameraLocation;
}pc;

layout(binding = 0)   uniform sampler2D  PositionImage;
layout(binding = 1)   uniform sampler2D  NormalImage;
layout(binding = 2)   uniform sampler2D  IrradianceStorageImage;
layout(binding = 3, rgba16f)   uniform image2D  SampledGIImage;
layout(binding = 4)   uniform sampler2D  VisibilityStorageImage;

layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;


void main() 
{

   int   Width            = int(pc.GridBaseLocation_ScreenSizeWidth.w);
   int   Height           = int(pc.ProbeSpacing_ScreenSizeHeight.w);
  

   ivec2 TextlCord        = ivec2(gl_GlobalInvocationID.xy);

   vec2 UV = (vec2(TextlCord) + 0.) / vec2(Width,Height); // + 0.5 gives us the middle of the TEXEL not the edge

   vec3 Position = texture(PositionImage,UV).rgb;
   vec3 Normal   = texture(NormalImage,  UV).rgb;
  
   vec3 Irradiance = vec3(0);

   vec3 SamplePosition = Position + (Normal * 1.2);

         if(dot(Normal, Normal) > 0.001){
          Irradiance = SampleIrradiance(
              IrradianceStorageImage,
              VisibilityStorageImage,
              SamplePosition,
              Normal,
              pc.GridBaseLocation_ScreenSizeWidth.xyz,
              pc.ProbeSpacing_ScreenSizeHeight.xyz,
              ivec3(pc.ProbeCount.xyz),
              // Irradiance Params
              pc.ProbeSideLength,
              pc.GutterSize,
              pc.AtlasWidthSize,
              // Visibility Params
              pc.ProbeSideLength,   //Same values are being passed cus as of now they are both the same size. but this can be changed
              pc.GutterSize,
              pc.AtlasWidthSize,pc.CameraLocation.xyz
          );
      };

   imageStore(SampledGIImage, ivec2(gl_GlobalInvocationID.xy), vec4(Irradiance,1));
}
